/* ============================================================
   2026 — ARCHIVED SEASON, loaded by the site
   ------------------------------------------------------------
   GENERATED by tools/rollover.js. Don't hand-edit: it is the five
   data files beside it, wrapped so their top-level declarations
   become function-locals instead of page globals. Without that,
   this season's SEASON/COACHES/TEAM_SCHEDULES would collide with
   the live season's and the page would fail to start.

   Edit the files next to this one if a fact about 2026 is wrong,
   then regenerate. Better still: don't. This is history.
   ============================================================ */
(function () {
  "use strict";

  var season = (function () {
    /* ---- league-data.js ---- */
    /* ============================================================
       3-STAR DYNASTY — roster, season state, and power rankings
       ------------------------------------------------------------
       Same shape as every other league's league-data.js. script.js and
       style.css are shared from the repo root and need no changes.

       Split of duties:
         league-data.js    who's in the league, what week it is, the poll
         schedule-data.js  each team's 16-week schedule + scores
       ============================================================ */

    /* ------------------------------------------------------------
       SEASON STATE — manually advanced, never date-driven.

       currentWeek: "PRESEASON" until Week 0 kicks off in-game, then
       the week number (0-15) currently being played.

       The advance deadline is the only real-world date on the site, and
       it's stored twice: nextAdvanceAt is the authored value and
       nextAdvance is the sentence generated from it. See the long note
       in main/league-data.js — neither should be hand-edited, and both
       go blank together to hide the countdown line.

       Like 1-star, this league names a day and not a clock time, so the
       stored value is a bare date and the badge carries no clock time.
       A bare date resolves to 10 PM Eastern internally, used only to
       decide whether an advance is still ahead; that never reaches the
       site.
       ------------------------------------------------------------ */
    const SEASON = {
      // In-game year for this season's data. See the long note in
      // main/league-data.js — it governs the seasons/<year>/ archive.
      year: 2026,

      currentWeek: "OFFSEASON",
      statusLine: "OFFSEASON",
      /* Entered as "Monday, August 13th" on the Week 9 advance, back
         when this was free text. The 13th is a Thursday — the date was
         right and the weekday was the typo, so the generated text says
         Thursday now. This is the class of mistake the picker removes:
         nobody types the weekday any more. */
      nextAdvanceAt: "",
      nextAdvance: "",
    };

    /* ------------------------------------------------------------
       LEAGUE IDENTITY
       ------------------------------------------------------------ */
    const LEAGUE_INFO = {
      name: "NCAA Legends",
      tag: "3-Star Dynasty",

      links: {
        discord: "",
        rules: "",
      },

      useEspnLogos: true,
    };

    /* ------------------------------------------------------------
       COACHES — from the Active Roster tab, snapshot 2026-07-21.

       TEAM NAMES are expanded from the sign-up sheet's shorthand so
       they read consistently with the other leagues and so the ESPN
       logo lookup is unambiguous:
         Cal -> California      ISU  -> Iowa State
         JMU -> James Madison   NDSU -> North Dakota State
         Pitt -> Pittsburgh     VA Tech -> Virginia Tech

       CONFERENCES are the league's own custom realignment, not the
       real-world alignment — James Madison, North Texas, Charlotte and
       North Dakota State genuinely sit in this league's SEC. Don't
       "correct" these to stock conferences.

       espnId values are unverified — open /logo-check.html to eyeball
       them all at once. A wrong id silently renders another school's
       logo; a missing one just falls back to the monogram chip.
       ------------------------------------------------------------ */
    const COACHES = [
      { name: "Bl00dVayN3",      team: "California",         conference: "ACC", color: "#FDB515", twitch: "https://www.twitch.tv/bl00dvayn3", espnId: "25" },
      { name: "Temptiger",       team: "James Madison",      conference: "SEC", color: "#9B6BD8", twitch: "https://www.twitch.tv/temptiger", espnId: "256" },
      { name: "DiabeticSnail22", team: "North Texas",        conference: "SEC", color: "#35B06A", twitch: "https://www.twitch.tv/diabeticsnail22", espnId: "249", departedAfterWeek: 4 },  // Went inactive here after Week 4; still active in the main dynasty. Weeks 0-4 stand (Texan_hog keeps the Week 4 loss); North Texas is CPU from Week 5. See the flag notes in main/league-data.js.
      { name: "Brian52682",      team: "Baylor",             conference: "XII", color: "#F5C542", twitch: "https://www.twitch.tv/brian52682", espnId: "239" },
      { name: "Dway",            team: "Iowa State",         conference: "XII", color: "#D6394E", twitch: "https://www.twitch.tv/dwayinspired", espnId: "66" },
      { name: "Salzy",           team: "Wisconsin",          conference: "B1G", color: "#D63B45", twitch: "https://www.twitch.tv/salzy117", espnId: "275" },
      { name: "Oldarmy324",      team: "Pittsburgh",         conference: "ACC", color: "#F5C542", twitch: "https://www.twitch.tv/oldarmy324", espnId: "221" },
      { name: "Cleveland",       team: "Virginia Tech",      conference: "ACC", color: "#E8703F", twitch: "https://www.twitch.tv/buckeyefan_", espnId: "259", departedAfterWeek: 14 },  // Left the league from week 15, the same way Trick whitey did — weeks 0-14 stand as real head-to-head games; Virginia Tech is CPU from week 15 on, so Oldarmy324's ACC Championship win over Virginia Tech is a CPU game, and so is RonRicoFSU's Pop-Tarts Bowl.
      { name: "Trick whitey",    team: "Maryland",           conference: "B1G", color: "#FFD24D", twitch: "https://www.twitch.tv/trickwhitey44", espnId: "120", departedAfterWeek: 14 },  // Left the league during championship week for personal reasons — weeks 0-14 stand as real head-to-head games; Maryland is CPU from week 15 on, so Salzy's Big Ten Championship win over Maryland is a CPU game, not a head-to-head result. Also left the main dynasty (Alabama) in the same move.
      { name: "Texan_hog",       team: "North Dakota State", conference: "SEC", color: "#35B86A", twitch: "https://www.twitch.tv/texan_hog08", espnId: "2449" },
      { name: "RonRicoFSU",      team: "Colorado",           conference: "XII", color: "#CFB87C", twitch: "https://www.twitch.tv/ronricofsu", espnId: "38" },
      { name: "EHDC12",          team: "North Carolina",     conference: "ACC", color: "#7BAFD4", twitch: "https://www.twitch.tv/DCGQManOfTheYear7", espnId: "153" },
      { name: "wacky9speedy",    team: "Charlotte",          conference: "SEC", color: "#4FAE84", twitch: "https://www.twitch.tv/wacky9speedy", espnId: "2429" },
      { name: "EYEDONTPULL19",   team: "UCF",                conference: "XII", color: "#E0C158", twitch: "", espnId: "2116" },
      { name: "Miles",           team: "Rutgers",            conference: "B1G", color: "#E03A57", twitch: "https://www.twitch.tv/kyrvach", espnId: "164", joinedAtWeek: 11 },  // Took Rutgers over from CoachLawless, who held the spot as `active: false` and never played a game. Weeks 0-10 were played by the CPU and stay CPU — in particular Trick whitey's Week 7 win over Rutgers is NOT a head-to-head result. Same Miles as the main dynasty (Georgia): one Twitch, and one shared entry in tools/config.json for Discord pings.
    ];

    /* ------------------------------------------------------------
       POWER RANKINGS

       Empty until enough H2H (user vs. user) games are on the board.
       The Rankings tab shows an explanatory empty state until this
       array has rows. Shape:
         { week: 3, rank: 1, team: "Wisconsin", record: "3-0", score: 97.5 }
       ------------------------------------------------------------ */
    const RANKINGS = [];


    /* ---- schedule-data.js ---- */
    /* ============================================================
       3-STAR DYNASTY — SCHEDULE DATA
       ------------------------------------------------------------
       Transcribed from in-game "Team Schedule" screenshots, 2 per
       team (weeks 0-8 and weeks 8-16), overlap deduped by hand.
       Snapshot taken 2026-07-21, mid Week 0.

       All 15 coaches are represented. Every user-vs-user matchup was
       cross-checked against BOTH coaches' screenshots and the home/away
       sides agree in all cases.

       WEEK MAPPING. The in-game table lists rows 0-14, then
       "Conf Champ", then 16. This file follows the convention the
       main dynasty already uses and that script.js's weekLabel()
       expects:
           weeks 0-13   regular season games
           week 14      Army-Navy Week
           week 15      conference championship
           weeks 16-19  Bowl Weeks 1-4 (CFP rounds + bowls)

       THE POSTSEASON LIVES HERE TOO — weeks 15-19. A conference
       championship, a bowl or a CFP round that a COACHED team played is
       an ordinary row on that team's schedule, with three optional extra
       fields:

         neutral: true      no true home team. home/away still decide
                            which score is which; the row renders "VS" at
                            the named stadium rather than claiming "AT".
         title: "Rose Bowl" the game's own name. Replaces the week number
                            in the schedule row and the card footer.
         round: "cfp-qf"    the machine-readable round id. One of:
                            ccg, bowl-w1, bowl-w2,
                            cfp-r1, cfp-qf, cfp-sf, cfp-nc

       `round` IS LOAD-BEARING AND `title` IS NOT. Conference titles, CFP
       appearances and national championships on the roster cards are
       derived by matching `round`; a bowl game with a title and no round
       renders correctly and earns nothing. The round is never inferred
       from the title, because a sponsor renaming a bowl would silently
       stop counting it.

         { week: 17, opponent: "Miami", location: "vs", neutral: true,
           stadium: "AT&T Stadium", title: "Cotton Bowl", round: "cfp-qf",
           teamScore: 31, opponentScore: 24 }

       A game between two teams NOBODY coaches — most of the CFP bracket
       — has no coach's schedule to live on and goes in
       postseason-data.js instead.
       The trailing in-game row 16 (a post-CCG bye for everyone) is
       not carried over — nothing renders it.

       STADIUMS. The Team Schedule screen doesn't display venue, so
       stadium is intentionally omitted. script.js treats it as
       optional (renders an empty span), so the site is happy without
       it. Can be filled in per entry later if it's wanted.

       SCORES. Week 0 finals are recorded as teamScore/opponentScore
       from that team's own perspective. Every week 0 result so far is
       against a CPU opponent, so there's no second entry to keep in
       sync. Once a user-vs-user game goes final, add the score to BOTH
       teams' entries or it'll only show on one coach's schedule.

       NAME NOTE: Pittsburgh's week 1 opponent is "Miami University"
       (the Ohio RedHawks) — distinct from "Miami" (the ACC Hurricanes),
       who appear on the North Carolina, Pittsburgh and Virginia Tech
       schedules. Both are spelled as the game spells them; don't
       collapse them into one name.

       CONFERENCES use this league's custom realignment, matching
       league-data.js (ACC / SEC / XII / B1G) — James Madison, North
       Texas, Charlotte and North Dakota State really are in the SEC
       here. Don't "correct" them to stock alignment.
       ============================================================ */
    const TEAM_SCHEDULES = [
      /* ---------------------------- ACC ---------------------------- */
      {
        team: "California",
        conference: "ACC",
        weeks: [
          { week: 0, opponent: "Nevada", location: "vs", teamScore: 52, opponentScore: 24 },
          { week: 1, opponent: "UCLA", location: "vs", teamScore: 23, opponentScore: 20 },
          { week: 2, opponent: "Syracuse", location: "at", teamScore: 22, opponentScore: 10 },
          { week: 3, opponent: "FCS West", location: "vs", teamScore: 40, opponentScore: 14 },
          { week: 4, opponent: "Clemson", location: "vs", teamScore: 27, opponentScore: 10 },
          { week: 5, note: "BYE" },
          { week: 6, opponent: "Virginia Tech", location: "vs", teamScore: 16, opponentScore: 45 },
          { week: 7, opponent: "Wake Forest", location: "vs", teamScore: 44, opponentScore: 41 },
          { week: 8, opponent: "SMU", location: "at", teamScore: 35, opponentScore: 17 },
          { week: 9, opponent: "NC State", location: "at", teamScore: 23, opponentScore: 6 },
          { week: 10, note: "BYE" },
          { week: 11, opponent: "Virginia", location: "at", teamScore: 45, opponentScore: 14 },
          { week: 12, opponent: "Stanford", location: "vs", teamScore: 41, opponentScore: 0 },
          { week: 13, opponent: "Pittsburgh", location: "vs", teamScore: 24, opponentScore: 45 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Washington State", location: "at", neutral: true, title: "Holiday Bowl", round: "bowl-w1", teamScore: 28, opponentScore: 24 },
        ],
      },
      {
        team: "North Carolina",
        conference: "ACC",
        weeks: [
          { week: 0, opponent: "TCU", location: "vs", teamScore: 38, opponentScore: 28 },
          { week: 1, note: "BYE" },
          { week: 2, opponent: "FCS Southeast", location: "vs", teamScore: 35, opponentScore: 3 },
          { week: 3, opponent: "Clemson", location: "at", teamScore: 17, opponentScore: 14 },
          { week: 4, note: "BYE" },
          { week: 5, opponent: "Notre Dame", location: "vs", teamScore: 13, opponentScore: 20 },
          { week: 6, opponent: "Pittsburgh", location: "at", teamScore: 6, opponentScore: 24 },
          { week: 7, opponent: "Duke", location: "at", teamScore: 17, opponentScore: 10 },
          { week: 8, opponent: "Syracuse", location: "vs", teamScore: 31, opponentScore: 3 },
          { week: 9, opponent: "Miami", location: "vs", teamScore: 10, opponentScore: 41 },
          { week: 10, opponent: "UConn", location: "at", teamScore: 48, opponentScore: 17 },
          { week: 11, opponent: "Louisville", location: "vs", teamScore: 17, opponentScore: 34 },
          { week: 12, opponent: "Virginia", location: "at", teamScore: 21, opponentScore: 36 },
          { week: 13, opponent: "NC State", location: "vs", teamScore: 7, opponentScore: 26 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Tulane", location: "vs", neutral: true, title: "Military Bowl", round: "bowl-w1", teamScore: 37, opponentScore: 34 },
        ],
      },
      {
        team: "Pittsburgh",
        conference: "ACC",
        weeks: [
          { week: 0, opponent: "West Virginia", location: "vs", teamScore: 37, opponentScore: 13 },
          { week: 1, opponent: "Miami University", location: "vs", teamScore: 28, opponentScore: 0 },
          { week: 2, note: "BYE" },
          { week: 3, opponent: "Syracuse", location: "vs", teamScore: 27, opponentScore: 20 },
          { week: 4, opponent: "FCS East", location: "vs", teamScore: 45, opponentScore: 10 },
          { week: 5, opponent: "Virginia Tech", location: "at", teamScore: 7, opponentScore: 35 },
          { week: 6, opponent: "North Carolina", location: "vs", teamScore: 24, opponentScore: 6 },
          { week: 7, opponent: "Boston College", location: "at", teamScore: 41, opponentScore: 0 },
          { week: 8, opponent: "Miami", location: "at", teamScore: 27, opponentScore: 22 },
          { week: 9, opponent: "Georgia Tech", location: "vs", teamScore: 30, opponentScore: 17 },
          { week: 10, note: "BYE" },
          { week: 11, opponent: "Florida State", location: "vs", teamScore: 40, opponentScore: 21 },
          { week: 12, opponent: "Louisville", location: "at", teamScore: 31, opponentScore: 27 },
          { week: 13, opponent: "California", location: "at", teamScore: 45, opponentScore: 24 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "Virginia Tech", location: "at", neutral: true, title: "ACC Championship", round: "ccg", teamScore: 31, opponentScore: 10 },
          { week: 16, note: "CFP First Round BYE" },
          { week: 17, opponent: "South Carolina", location: "vs", neutral: true, title: "Peach Bowl", round: "cfp-qf", teamScore: 27, opponentScore: 13 },
          { week: 18, opponent: "Oregon", location: "vs", neutral: true, title: "Sugar Bowl", round: "cfp-sf", teamScore: 16, opponentScore: 13 },
          { week: 19, opponent: "Wisconsin", location: "vs", neutral: true, title: "National Championship", round: "cfp-nc", teamScore: 28, opponentScore: 17 },
        ],
      },
      {
        team: "Virginia Tech",
        conference: "ACC",
        weeks: [
          { week: 0, opponent: "Western Michigan", location: "vs", teamScore: 24, opponentScore: 34 },
          { week: 1, opponent: "FCS East", location: "vs", teamScore: 49, opponentScore: 0 },
          { week: 2, opponent: "Old Dominion", location: "vs", teamScore: 35, opponentScore: 10 },
          { week: 3, note: "BYE" },
          { week: 4, opponent: "Boston College", location: "at", teamScore: 22, opponentScore: 15 },
          { week: 5, opponent: "Pittsburgh", location: "vs", teamScore: 35, opponentScore: 7 },
          { week: 6, opponent: "California", location: "at", teamScore: 45, opponentScore: 16 },
          { week: 7, opponent: "Georgia Tech", location: "vs", teamScore: 24, opponentScore: 7 },
          { week: 8, opponent: "Clemson", location: "at", teamScore: 7, opponentScore: 9 },
          { week: 9, note: "BYE" },
          { week: 10, opponent: "SMU", location: "at", teamScore: 27, opponentScore: 26 },
          { week: 11, opponent: "Stanford", location: "vs", teamScore: 21, opponentScore: 18 },
          { week: 12, opponent: "Miami", location: "at", teamScore: 20, opponentScore: 7 },
          { week: 13, opponent: "Virginia", location: "vs", teamScore: 33, opponentScore: 28 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "Pittsburgh", location: "vs", neutral: true, title: "ACC Championship", round: "ccg", teamScore: 10, opponentScore: 31 },
          { week: 16, opponent: "Colorado", location: "vs", neutral: true, title: "Pop-Tarts Bowl", round: "bowl-w1" },
        ],
      },

      /* ---------------------------- B1G ---------------------------- */
      {
        team: "Maryland",
        conference: "B1G",
        /* Trick whitey left the league during championship week
           (departedAfterWeek: 14 in league-data.js). Weeks 0-14 are his
           and stay head-to-head. The Week 15 Big Ten Championship is not:
           Maryland was CPU by then and Salzy played the CPU, so that
           42-38 must not enter either coach's H2H record or power-poll
           window. isLeagueTeam("Maryland", 15) returns false, which is
           what keeps that true. The result is transcribed on both blocks
           anyway so the By Team pages agree with each other. */
        weeks: [
          { week: 0, opponent: "Marshall", location: "vs", teamScore: 38, opponentScore: 10 },
          { week: 1, opponent: "FCS East", location: "vs", teamScore: 73, opponentScore: 3 },
          { week: 2, opponent: "Utah", location: "vs", teamScore: 45, opponentScore: 28 },
          { week: 3, note: "BYE" },
          { week: 4, opponent: "UCLA", location: "vs", teamScore: 33, opponentScore: 23 },
          { week: 5, opponent: "Nebraska", location: "at", teamScore: 28, opponentScore: 24 },
          { week: 6, opponent: "Ohio State", location: "at", teamScore: 31, opponentScore: 0 },
          { week: 7, opponent: "Rutgers", location: "vs", teamScore: 45, opponentScore: 19 },
          { week: 8, note: "BYE" },
          { week: 9, opponent: "Illinois", location: "vs", teamScore: 63, opponentScore: 3 },
          { week: 10, opponent: "Purdue", location: "at", teamScore: 45, opponentScore: 7 },
          { week: 11, opponent: "Wisconsin", location: "vs", teamScore: 28, opponentScore: 25 },
          { week: 12, opponent: "USC", location: "at", teamScore: 56, opponentScore: 13 },
          { week: 13, opponent: "Penn State", location: "vs", teamScore: 37, opponentScore: 22 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "Wisconsin", location: "vs", neutral: true, title: "Big Ten Championship", round: "ccg", teamScore: 42, opponentScore: 38, sim: true },
        ],
      },
      {
        team: "Rutgers",
        conference: "B1G",
        /* Weeks 1-10 were played by the CPU — the spot was held but
           unplayed until Miles took it over at Week 11 (joinedAtWeek in
           league-data.js). The results are transcribed anyway so his
           schedule page isn't half empty and the site can show the record
           he inherited.

           They are recorded here as CPU results and must stay that way.
           The Week 7 loss at Maryland is the one to watch: Trick whitey's
           block already carries it as 45-19 and the two entries agree,
           but it is NOT a head-to-head game and it must not enter either
           coach's H2H record or power-poll window. isLeagueTeam("Rutgers",
           7) returns false, which is what keeps that true. Same for the
           Week 10 loss at Wisconsin, 48-16 on Salzy's block. */
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "UMass", location: "vs", teamScore: 21, opponentScore: 9 },
          { week: 2, opponent: "Boston College", location: "at", teamScore: 24, opponentScore: 21 },
          { week: 3, opponent: "USC", location: "vs", teamScore: 24, opponentScore: 38 },
          { week: 4, opponent: "FCS East", location: "vs", teamScore: 34, opponentScore: 6 },
          { week: 5, opponent: "Indiana", location: "vs", teamScore: 21, opponentScore: 38 },
          { week: 6, note: "BYE" },
          { week: 7, opponent: "Maryland", location: "at", teamScore: 19, opponentScore: 45 },
          { week: 8, opponent: "Northwestern", location: "at", teamScore: 21, opponentScore: 24 },
          { week: 9, opponent: "Michigan", location: "vs", teamScore: 10, opponentScore: 23 },
          { week: 10, opponent: "Wisconsin", location: "at", teamScore: 16, opponentScore: 48 },
          { week: 11, opponent: "Nebraska", location: "vs", teamScore: 35, opponentScore: 38 },
          { week: 12, opponent: "Penn State", location: "at", teamScore: 35, opponentScore: 37 },
          { week: 13, opponent: "Michigan State", location: "vs", teamScore: 27, opponentScore: 24 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
        ],
      },
      {
        team: "Wisconsin",
        conference: "B1G",
        weeks: [
          { week: 0, opponent: "UConn", location: "vs", teamScore: 49, opponentScore: 10 },
          { week: 1, opponent: "Notre Dame", location: "at", teamScore: 27, opponentScore: 24 },
          { week: 2, note: "BYE" },
          { week: 3, opponent: "Eastern Michigan", location: "vs", teamScore: 55, opponentScore: 34 },
          { week: 4, opponent: "Penn State", location: "at", teamScore: 20, opponentScore: 19 },
          { week: 5, opponent: "Michigan State", location: "vs", teamScore: 42, opponentScore: 7 },
          { week: 6, note: "BYE" },
          { week: 7, opponent: "UCLA", location: "at", teamScore: 31, opponentScore: 24 },
          { week: 8, opponent: "USC", location: "vs", teamScore: 20, opponentScore: 17 },
          { week: 9, opponent: "Iowa", location: "at", teamScore: 35, opponentScore: 20 },
          { week: 10, opponent: "Rutgers", location: "vs", teamScore: 48, opponentScore: 16 },
          { week: 11, opponent: "Maryland", location: "at", teamScore: 25, opponentScore: 28 },
          { week: 12, opponent: "Purdue", location: "at", teamScore: 45, opponentScore: 24 },
          { week: 13, opponent: "Minnesota", location: "vs", teamScore: 29, opponentScore: 13 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "Maryland", location: "at", neutral: true, title: "Big Ten Championship", round: "ccg", teamScore: 38, opponentScore: 42, sim: true },
          { week: 16, opponent: "Tennessee", location: "vs", neutral: true, round: "cfp-r1", teamScore: 38, opponentScore: 7 },
          { week: 17, opponent: "Georgia", location: "at", neutral: true, title: "Cotton Bowl", round: "cfp-qf", teamScore: 31, opponentScore: 20 },
          { week: 18, opponent: "Maryland", location: "at", neutral: true, title: "Orange Bowl", round: "cfp-sf", teamScore: 28, opponentScore: 14 },
          { week: 19, opponent: "Pittsburgh", location: "at", neutral: true, title: "National Championship", round: "cfp-nc", teamScore: 17, opponentScore: 28 },
        ],
      },

      /* ---------------------------- XII ---------------------------- */
      {
        team: "Baylor",
        conference: "XII",
        weeks: [
          { week: 0, opponent: "Troy", location: "vs", teamScore: 42, opponentScore: 7 },
          { week: 1, opponent: "Auburn", location: "at", teamScore: 31, opponentScore: 7 },
          { week: 2, note: "BYE" },
          { week: 3, opponent: "Louisiana Tech", location: "vs", teamScore: 73, opponentScore: 14 },
          { week: 4, opponent: "Colorado", location: "vs", teamScore: 16, opponentScore: 23 },
          { week: 5, opponent: "Arizona State", location: "at", teamScore: 38, opponentScore: 27 },
          { week: 6, note: "BYE" },
          { week: 7, opponent: "TCU", location: "vs", teamScore: 54, opponentScore: 28 },
          { week: 8, opponent: "Kansas", location: "at", teamScore: 35, opponentScore: 17 },
          { week: 9, opponent: "UCF", location: "at", teamScore: 28, opponentScore: 56 },
          { week: 10, opponent: "Iowa State", location: "vs", teamScore: 45, opponentScore: 14 },
          { week: 11, opponent: "BYU", location: "at", teamScore: 16, opponentScore: 34 },
          { week: 12, opponent: "Texas Tech", location: "vs", teamScore: 31, opponentScore: 14 },
          { week: 13, opponent: "Houston", location: "at", teamScore: 26, opponentScore: 14 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 17, opponent: "North Dakota State", location: "vs", neutral: true, title: "Texas Bowl", round: "bowl-w2", teamScore: 31, opponentScore: 17 },
        ],
      },
      {
        team: "Colorado",
        conference: "XII",
        weeks: [
          { week: 0, opponent: "Utah State", location: "vs", teamScore: 45, opponentScore: 16 },
          { week: 1, opponent: "Georgia Tech", location: "at", teamScore: 42, opponentScore: 24 },
          { week: 2, note: "BYE" },
          { week: 3, opponent: "Northwestern", location: "at", teamScore: 17, opponentScore: 28 },
          { week: 4, opponent: "Baylor", location: "at", teamScore: 23, opponentScore: 16 },
          { week: 5, opponent: "Texas Tech", location: "vs", teamScore: 14, opponentScore: 59 },
          { week: 6, note: "BYE" },
          { week: 7, opponent: "Utah", location: "vs", teamScore: 42, opponentScore: 28 },
          { week: 8, opponent: "Oklahoma State", location: "at", teamScore: 28, opponentScore: 25 },
          { week: 9, opponent: "Kansas State", location: "vs", teamScore: 45, opponentScore: 17 },
          { week: 10, opponent: "Arizona State", location: "at", teamScore: 35, opponentScore: 31 },
          { week: 11, opponent: "Houston", location: "vs", teamScore: 49, opponentScore: 21 },
          { week: 12, opponent: "Cincinnati", location: "at", teamScore: 42, opponentScore: 7 },
          { week: 13, opponent: "UCF", location: "vs", teamScore: 22, opponentScore: 45 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Virginia Tech", location: "at", neutral: true, title: "Pop-Tarts Bowl", round: "bowl-w1", teamScore: 42, opponentScore: 17 },
        ],
      },
      {
        team: "Iowa State",
        conference: "XII",
        weeks: [
          { week: 0, opponent: "Toledo", location: "vs", teamScore: 27, opponentScore: 6 },
          { week: 1, opponent: "FCS Midwest", location: "vs", teamScore: 38, opponentScore: 22 },
          { week: 2, opponent: "Iowa", location: "at", teamScore: 24, opponentScore: 0 },
          { week: 3, note: "BYE" },
          { week: 4, opponent: "Utah", location: "vs", teamScore: 14, opponentScore: 10 },
          { week: 5, opponent: "West Virginia", location: "vs", teamScore: 20, opponentScore: 14 },
          { week: 6, opponent: "BYU", location: "at", teamScore: 28, opponentScore: 22 },
          { week: 7, note: "BYE" },
          { week: 8, opponent: "Arizona", location: "at", teamScore: 19, opponentScore: 24 },
          { week: 9, opponent: "Oklahoma State", location: "vs", teamScore: 21, opponentScore: 31 },
          { week: 10, opponent: "Baylor", location: "at", teamScore: 14, opponentScore: 45 },
          { week: 11, opponent: "Cincinnati", location: "vs", teamScore: 38, opponentScore: 17 },
          { week: 12, opponent: "UCF", location: "at", teamScore: 10, opponentScore: 41, sim: true },
          { week: 13, opponent: "Kansas State", location: "vs", teamScore: 28, opponentScore: 14 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Texas", location: "at", neutral: true, title: "Liberty Bowl", round: "bowl-w1", teamScore: 13, opponentScore: 31 },
        ],
      },
      {
        team: "UCF",
        conference: "XII",
        weeks: [
          { week: 0, opponent: "USF", location: "vs", teamScore: 28, opponentScore: 21 },
          { week: 1, opponent: "FCS Southeast", location: "vs", teamScore: 38, opponentScore: 7 },
          { week: 2, note: "BYE" },
          { week: 3, opponent: "Georgia State", location: "vs", teamScore: 30, opponentScore: 0 },
          { week: 4, opponent: "TCU", location: "vs", teamScore: 28, opponentScore: 14 },
          { week: 5, opponent: "Houston", location: "at", teamScore: 27, opponentScore: 35 },
          { week: 6, opponent: "Oklahoma State", location: "at", teamScore: 31, opponentScore: 21 },
          { week: 7, note: "BYE" },
          { week: 8, opponent: "BYU", location: "vs", teamScore: 28, opponentScore: 23 },
          { week: 9, opponent: "Baylor", location: "vs", teamScore: 56, opponentScore: 28 },
          { week: 10, opponent: "Kansas", location: "at", teamScore: 24, opponentScore: 14 },
          { week: 11, opponent: "Arizona State", location: "vs", teamScore: 35, opponentScore: 30 },
          { week: 12, opponent: "Iowa State", location: "vs", teamScore: 41, opponentScore: 10, sim: true },
          { week: 13, opponent: "Colorado", location: "at", teamScore: 45, opponentScore: 22 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "BYU", location: "vs", neutral: true, title: "Big 12 Championship", round: "ccg", teamScore: 0, opponentScore: 31 },
          { week: 16, opponent: "South Carolina", location: "at", neutral: true, round: "cfp-r1", teamScore: 17, opponentScore: 27 },
        ],
      },

      /* ---------------------------- SEC ---------------------------- */
      {
        team: "Charlotte",
        conference: "SEC",
        weeks: [
          { week: 0, opponent: "Tulsa", location: "vs", teamScore: 33, opponentScore: 14 },
          { week: 1, opponent: "Georgia", location: "at", teamScore: 7, opponentScore: 52 },
          { week: 2, opponent: "Ole Miss", location: "at", teamScore: 28, opponentScore: 34 },
          { week: 3, opponent: "FCS Southeast", location: "vs", teamScore: 31, opponentScore: 10 },
          { week: 4, note: "BYE" },
          { week: 5, opponent: "James Madison", location: "vs", teamScore: 10, opponentScore: 45 },
          { week: 6, opponent: "Oklahoma", location: "vs", teamScore: 38, opponentScore: 10 },
          { week: 7, opponent: "North Dakota State", location: "vs", teamScore: 3, opponentScore: 21 },
          { week: 8, opponent: "Arkansas", location: "at", teamScore: 7, opponentScore: 34 },
          { week: 9, opponent: "Texas", location: "at", teamScore: 7, opponentScore: 14 },
          { week: 10, opponent: "UAB", location: "vs", teamScore: 32, opponentScore: 6 },
          { week: 11, opponent: "Florida", location: "vs", teamScore: 7, opponentScore: 19 },
          { week: 12, opponent: "LSU", location: "at", teamScore: 31, opponentScore: 28 },
          { week: 13, note: "BYE" },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
        ],
      },
      {
        team: "James Madison",
        conference: "SEC",
        weeks: [
          { week: 0, opponent: "Southern Mississippi", location: "at", teamScore: 42, opponentScore: 24 },
          { week: 1, opponent: "Liberty", location: "vs", teamScore: 44, opponentScore: 14 },
          { week: 2, opponent: "LSU", location: "vs", teamScore: 20, opponentScore: 27 },
          { week: 3, note: "BYE" },
          { week: 4, opponent: "Auburn", location: "vs", teamScore: 45, opponentScore: 14 },
          { week: 5, opponent: "Charlotte", location: "at", teamScore: 45, opponentScore: 10 },
          { week: 6, opponent: "Alabama", location: "at", teamScore: 35, opponentScore: 17 },
          { week: 7, opponent: "Ole Miss", location: "vs", teamScore: 32, opponentScore: 37 },
          { week: 8, opponent: "North Texas", location: "at", teamScore: 49, opponentScore: 14 },
          { week: 9, opponent: "Tennessee", location: "vs", teamScore: 24, opponentScore: 41 },
          { week: 10, note: "BYE" },
          { week: 11, opponent: "UConn", location: "at", teamScore: 45, opponentScore: 38 },
          { week: 12, opponent: "Georgia", location: "at", teamScore: 28, opponentScore: 34 },
          { week: 13, opponent: "Oklahoma", location: "at", teamScore: 7, opponentScore: 45 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "UAB", location: "at", neutral: true, title: "Armed Forces Bowl", round: "bowl-w1", teamScore: 45, opponentScore: 24 },
        ],
      },
      {
        team: "North Dakota State",
        conference: "SEC",
        weeks: [
          { week: 0, opponent: "Jacksonville State", location: "vs", teamScore: 40, opponentScore: 14 },
          { week: 1, opponent: "Oklahoma", location: "vs", teamScore: 48, opponentScore: 17 },
          { week: 2, opponent: "Georgia", location: "vs", teamScore: 31, opponentScore: 51 },
          { week: 3, opponent: "FCS Northwest", location: "vs", teamScore: 56, opponentScore: 7 },
          { week: 4, opponent: "North Texas", location: "at", teamScore: 48, opponentScore: 56 },
          { week: 5, opponent: "Texas", location: "vs", teamScore: 42, opponentScore: 38 },
          { week: 6, opponent: "Auburn", location: "at", teamScore: 21, opponentScore: 38 },
          { week: 7, opponent: "Charlotte", location: "at", teamScore: 21, opponentScore: 3 },
          { week: 8, note: "BYE" },
          { week: 9, opponent: "Kentucky", location: "at", teamScore: 25, opponentScore: 28 },
          { week: 10, opponent: "Tennessee", location: "at", teamScore: 19, opponentScore: 0 },
          { week: 11, opponent: "Arkansas", location: "vs", teamScore: 28, opponentScore: 20 },
          { week: 12, note: "BYE" },
          { week: 13, opponent: "Hawai'i", location: "at", teamScore: 35, opponentScore: 21 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 17, opponent: "Baylor", location: "at", neutral: true, title: "Texas Bowl", round: "bowl-w2", teamScore: 17, opponentScore: 31 },
        ],
      },
      {
        team: "North Texas",
        conference: "SEC",
        weeks: [
          { week: 0, opponent: "Indiana", location: "at", teamScore: 37, opponentScore: 26 },
          { week: 1, opponent: "Tennessee", location: "vs", teamScore: 45, opponentScore: 28 },
          { week: 2, opponent: "Texas A&M", location: "at", teamScore: 3, opponentScore: 45 },
          { week: 3, opponent: "Ole Miss", location: "at", teamScore: 56, opponentScore: 7 },
          { week: 4, opponent: "North Dakota State", location: "vs", teamScore: 56, opponentScore: 48 },
          { week: 5, note: "BYE" },
          { week: 6, opponent: "Arkansas", location: "at" },
          { week: 7, opponent: "LSU", location: "vs" },
          { week: 8, opponent: "James Madison", location: "vs" },
          { week: 9, opponent: "Tulane", location: "at" },
          { week: 10, opponent: "Rice", location: "vs" },
          { week: 11, opponent: "Kentucky", location: "at" },
          { week: 12, opponent: "Florida", location: "vs" },
          { week: 13, note: "BYE" },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
        ],
      },
    ];

    /* Schedule-team-name -> roster-team-name, for cases where the
       in-game team name doesn't match the sign-up sheet verbatim.

       Empty on purpose: every team above is written with the same
       expanded name league-data.js uses, so nothing needs remapping.
       If a future screenshot is transcribed with shorthand (e.g. "Cal",
       "NDSU", "VA Tech"), either expand it while transcribing or add
       the mapping here — validateData() logs a console warning for any
       schedule team no coach claims. */
    const SCHEDULE_TEAM_ALIASES = {};


    /* ---- top25-data.js ---- */
    /* ============================================================
       TOP 25 — the in-game AP poll, transcribed from screenshots
       ------------------------------------------------------------
       The 3-Star Dynasty's copy of the EA College Football 27 Top 25,
       one entry per week. It is NOT the site's own computed Power
       Rankings (that's the Rankings tab, built from head-to-head
       results). This poll is mostly CPU teams with a handful of coaches
       mixed in, and it drives two things on the site:

         1. The Top 25 tab.
         2. The "#N" rank badges on schedules. A game played in week N
            shows each team's rank from THAT week's poll, so a schedule
            always shows what a team was ranked WHEN the game was played,
            even after they rise or fall later.

       Because of (2), each week's poll is frozen history: once a week is
       entered, never edit it to reflect a later poll — add a new week
       instead.

       WHAT THE SITE SHOWS, AND WHEN (the reveal rule)
       The site shows the poll for SEASON.currentWeek — the week the season
       has actually advanced to — NOT simply the newest block in this file.
       So a poll added here for a week the site hasn't advanced to yet sits
       in the repo INVISIBLE, and reveals the moment someone advances to
       that week.

       NO ADVANCE GATE HERE (this is the difference from main)
       The main dynasty REFUSES to advance to week N until week N's poll is
       in its file, so the poll and the new week always surface together.
       3-star is deliberately not gated: advancing never waits on a
       screenshot. The cost is that the Top 25 tab can lag the schedule by
       a week when nobody's uploaded yet, which is the right trade for a
       league where the poll is a nice-to-have rather than the point. Drop
       a week in whenever it's convenient — including after the advance —
       and it appears as soon as it's pushed. See top25GateError() in
       tools/lib/league.js for where that choice is expressed.

       WHERE IT STARTS
       This file begins at the week 3-star started transcribing, not at
       week 1. Earlier weeks were never captured and won't be backfilled,
       so games before that week simply carry no rank badges — an absent
       poll renders as unranked, which is correct rather than broken.

       HOW TO ADD A WEEK
       Screenshot the in-game Top 25 for the week, then run:

         node tools/top25.js --league 3star --week N --file poll.txt

       The --league flag is the part that's easy to forget; without it the
       script writes to main. See tools/README.md. The tool counts to 25,
       catches a doubled rank, and won't let you quietly overwrite a week
       that's already history.

       Team names should match the roster / schedule spelling (the site
       resolves them the same way, through SCHEDULE_TEAM_ALIASES, so "Cal"
       vs "California" etc. still line up). `record` is whatever the poll
       shows next to the team.

         { rank, team, record }
           rank    1 = best, 1..25
           team    must resolve to a roster or schedule team name
           record  the W-L string shown in the poll (e.g. "1-0")
       ============================================================ */
    const TOP25 = [
      {
        week: 4,
        teams: [
          { rank: 1, team: "Texas", record: "3-0" },
          { rank: 2, team: "Miami", record: "4-0" },
          { rank: 3, team: "Oregon", record: "3-0" },
          { rank: 4, team: "Georgia", record: "3-0" },
          { rank: 5, team: "Ole Miss", record: "3-0" },
          { rank: 6, team: "Oklahoma", record: "3-1" },
          { rank: 7, team: "BYU", record: "3-0" },
          { rank: 8, team: "Ohio State", record: "2-1" },
          { rank: 9, team: "USC", record: "3-0" },
          { rank: 10, team: "Virginia", record: "2-0" },
          { rank: 11, team: "Indiana", record: "2-1" },
          { rank: 12, team: "Michigan", record: "2-1" },
          { rank: 13, team: "LSU", record: "3-1" },
          { rank: 14, team: "Alabama", record: "2-1" },
          { rank: 15, team: "South Carolina", record: "4-0" },
          { rank: 16, team: "Iowa", record: "2-1" },
          { rank: 17, team: "Louisville", record: "2-1" },
          { rank: 18, team: "Utah", record: "2-1" },
          { rank: 19, team: "Houston", record: "2-1" },
          { rank: 20, team: "Tennessee", record: "3-1" },
          { rank: 21, team: "Texas Tech", record: "2-1" },
          { rank: 22, team: "Missouri", record: "3-1" },
          { rank: 23, team: "Penn State", record: "2-2" },
          { rank: 24, team: "Texas A&M", record: "2-2" },
          { rank: 25, team: "Iowa State", record: "3-0" },
        ],
      },
      {
        week: 5,
        teams: [
          { rank: 1, team: "Miami", record: "5-0" },
          { rank: 2, team: "Georgia", record: "4-0" },
          { rank: 3, team: "Ole Miss", record: "4-0" },
          { rank: 4, team: "USC", record: "4-0" },
          { rank: 5, team: "Oklahoma", record: "4-1" },
          { rank: 6, team: "BYU", record: "4-0" },
          { rank: 7, team: "Ohio State", record: "3-1" },
          { rank: 8, team: "Texas", record: "3-2" },
          { rank: 9, team: "Virginia", record: "3-0" },
          { rank: 10, team: "Indiana", record: "3-1" },
          { rank: 11, team: "Michigan", record: "3-1" },
          { rank: 12, team: "Oregon", record: "3-1" },
          { rank: 13, team: "South Carolina", record: "5-0" },
          { rank: 14, team: "Tennessee", record: "4-1" },
          { rank: 15, team: "Louisville", record: "3-1" },
          { rank: 16, team: "Texas A&M", record: "3-2" },
          { rank: 17, team: "Texas Tech", record: "3-1" },
          { rank: 18, team: "Missouri", record: "4-1" },
          { rank: 19, team: "Iowa State", record: "5-0" },
          { rank: 20, team: "Arizona", record: "3-1" },
          { rank: 21, team: "California", record: "5-0" },
          { rank: 22, team: "LSU", record: "3-2" },
          { rank: 23, team: "Utah", record: "2-2" },
          { rank: 24, team: "Iowa", record: "2-2" },
          { rank: 25, team: "SMU", record: "2-2" },
        ],
      },
      {
        week: 6,
        teams: [
          { rank: 1, team: "Miami", record: "6-0" },
          { rank: 2, team: "Georgia", record: "5-0" },
          { rank: 3, team: "Ole Miss", record: "4-0" },
          { rank: 4, team: "USC", record: "5-0" },
          { rank: 5, team: "Oklahoma", record: "4-1" },
          { rank: 6, team: "BYU", record: "5-0" },
          { rank: 7, team: "Ohio State", record: "4-1" },
          { rank: 8, team: "Virginia", record: "4-0" },
          { rank: 9, team: "Indiana", record: "4-1" },
          { rank: 10, team: "Michigan", record: "4-1" },
          { rank: 11, team: "Oregon", record: "3-1" },
          { rank: 12, team: "Tennessee", record: "5-1" },
          { rank: 13, team: "Texas A&M", record: "4-2" },
          { rank: 14, team: "Texas Tech", record: "4-1" },
          { rank: 15, team: "Missouri", record: "5-1" },
          { rank: 16, team: "Iowa State", record: "5-0" },
          { rank: 17, team: "California", record: "5-0" },
          { rank: 18, team: "LSU", record: "4-2" },
          { rank: 19, team: "Utah", record: "2-2" },
          { rank: 20, team: "South Carolina", record: "5-1" },
          { rank: 21, team: "Notre Dame", record: "3-3" },
          { rank: 22, team: "Texas", record: "3-2" },
          { rank: 23, team: "Alabama", record: "2-2" },
          { rank: 24, team: "James Madison", record: "4-1" },
          { rank: 25, team: "Mississippi St", record: "6-0" },
        ],
      },
      {
        week: 7,
        teams: [
          { rank: 1, team: "Miami", record: "6-0" },
          { rank: 2, team: "Ole Miss", record: "5-0" },
          { rank: 3, team: "USC", record: "6-0" },
          { rank: 4, team: "Virginia", record: "5-0" },
          { rank: 5, team: "Georgia", record: "5-1" },
          { rank: 6, team: "Tennessee", record: "6-1" },
          { rank: 7, team: "Michigan", record: "4-1" },
          { rank: 8, team: "Oregon", record: "4-1" },
          { rank: 9, team: "Texas A&M", record: "5-2" },
          { rank: 10, team: "Iowa State", record: "6-0" },
          { rank: 11, team: "BYU", record: "5-1" },
          { rank: 12, team: "Texas Tech", record: "4-1" },
          { rank: 13, team: "Missouri", record: "5-1" },
          { rank: 14, team: "Utah", record: "3-2" },
          { rank: 15, team: "South Carolina", record: "5-1" },
          { rank: 16, team: "Notre Dame", record: "4-3" },
          { rank: 17, team: "Texas", record: "3-2" },
          { rank: 18, team: "Ohio State", record: "4-2" },
          { rank: 19, team: "James Madison", record: "5-1" },
          { rank: 20, team: "Oklahoma", record: "4-2" },
          { rank: 21, team: "Indiana", record: "4-2" },
          { rank: 22, team: "Mississippi St", record: "7-0" },
          { rank: 23, team: "Wisconsin", record: "5-0" },
          { rank: 24, team: "California", record: "5-1" },
          { rank: 25, team: "Kentucky", record: "5-1" },
        ],
      },
      {
        week: 8,
        teams: [
          { rank: 1, team: "Miami", record: "7-0" },
          { rank: 2, team: "Ole Miss", record: "6-0" },
          { rank: 3, team: "Georgia", record: "6-1" },
          { rank: 4, team: "USC", record: "6-0" },
          { rank: 5, team: "Tennessee", record: "7-1" },
          { rank: 6, team: "Oregon", record: "5-1" },
          { rank: 7, team: "Texas A&M", record: "6-2" },
          { rank: 8, team: "Iowa State", record: "6-0" },
          { rank: 9, team: "BYU", record: "5-1" },
          { rank: 10, team: "Texas Tech", record: "5-1" },
          { rank: 11, team: "Missouri", record: "6-1" },
          { rank: 12, team: "Virginia", record: "5-1" },
          { rank: 13, team: "South Carolina", record: "6-1" },
          { rank: 14, team: "Texas", record: "4-2" },
          { rank: 15, team: "Notre Dame", record: "4-3" },
          { rank: 16, team: "Ohio State", record: "5-2" },
          { rank: 17, team: "Oklahoma", record: "5-2" },
          { rank: 18, team: "Wisconsin", record: "6-0" },
          { rank: 19, team: "Mississippi St", record: "8-0" },
          { rank: 20, team: "California", record: "6-1" },
          { rank: 21, team: "Michigan", record: "4-2" },
          { rank: 22, team: "Maryland", record: "7-0" },
          { rank: 23, team: "James Madison", record: "5-2" },
          { rank: 24, team: "Michigan State", record: "6-1" },
          { rank: 25, team: "LSU", record: "5-3" },
        ],
      },
      {
        week: 9,
        teams: [
          { rank: 1, team: "Ole Miss", record: "7-0" },
          { rank: 2, team: "Georgia", record: "7-1" },
          { rank: 3, team: "Oregon", record: "6-1" },
          { rank: 4, team: "Tennessee", record: "8-1" },
          { rank: 5, team: "Texas A&M", record: "7-2" },
          { rank: 6, team: "Texas Tech", record: "6-1" },
          { rank: 7, team: "USC", record: "6-1" },
          { rank: 8, team: "Miami", record: "7-1" },
          { rank: 9, team: "Wisconsin", record: "8-0" },
          { rank: 10, team: "South Carolina", record: "7-1" },
          { rank: 11, team: "Notre Dame", record: "4-3" },
          { rank: 12, team: "Ohio State", record: "5-2" },
          { rank: 13, team: "Iowa State", record: "6-1" },
          { rank: 14, team: "Oklahoma", record: "5-2" },
          { rank: 15, team: "California", record: "8-1" },
          { rank: 16, team: "Mississippi State", record: "8-0" },
          { rank: 17, team: "Michigan", record: "5-2" },
          { rank: 18, team: "BYU", record: "5-2" },
          { rank: 19, team: "Michigan State", record: "7-1" },
          { rank: 20, team: "Maryland", record: "8-0" },
          { rank: 21, team: "James Madison", record: "6-3" },
          { rank: 22, team: "Arizona", record: "5-2" },
          { rank: 23, team: "LSU", record: "6-3" },
          { rank: 24, team: "UCF", record: "6-1" },
          { rank: 25, team: "Virginia", record: "5-2" },
        ],
      },
    ];


    /* ---- cfp-data.js ---- */
    /* ============================================================
       CFP — the College Football Playoff era of the season
       ------------------------------------------------------------
       From Week 10 the in-game poll stops being the AP Top 25 and
       becomes the CFP Top 25, and the game starts showing a projected
       12-team bracket alongside it. Both are transcribed here, one
       entry per week, and both are frozen history for the same reason
       top25-data.js is: the site renders what was true THAT week, so
       editing a past week silently rewrites the record.

       WHERE THE SEASON SWITCHES OVER
       Weeks 0-9    AP poll        -> top25-data.js
       Weeks 10-14  CFP Top 25     -> CFP_POLL below
                    + projected bracket -> CFP_BRACKET below
       Week 15      Conference championships. BRACKET ONLY — this is where
                    the projection becomes the real field. No poll block:
                    week 14 is Army-Navy, the rankings don't move off that
                    game, so week 15's poll IS week 14's and the site reads
                    it through the at-or-before fallback in script.js
                    rather than storing a duplicate. The advance gate
                    knows, and won't ask you for one.
       Weeks 16-19  Bowl Weeks 1-4, one per playoff round. NOTHING is
                    transcribed here: the poll froze at week 14 and the
                    bracket is already final. Only results change, and they
                    go in postseason-data.js — the bracket fills itself in
                    from them.

       If the rankings ever DO move at week 15, add a { week: 15 } block
       the normal way: the site prefers a real block over the fallback
       automatically, and nothing here needs changing to allow it.

       That boundary lives in ONE place in the code (CFP_ERA_WEEK in
       script.js). Nothing here needs to change if the game ever moves
       it.

       ------------------------------------------------------------
       CFP_POLL — the weekly CFP Top 25
       ------------------------------------------------------------
         const CFP_POLL = [
           { week: 10, teams: [ { rank, team, record }, ... x25 ] },
           { week: 11, teams: [ ... ] },
         ];

       Exactly the shape of a TOP25 block, deliberately — the same
       renderer draws it and the same "#N" schedule badges read it, so a
       week-11 game shows a team's week-11 CFP rank. week-core.js also
       reads CFP_POLL for postseason strength-of-schedule, and takes the
       LAST entry as the poll the bracket was seeded from.

       The single-object form (`{ teams: [...] }`, no week) is also
       accepted by week-core for a season where only the final seeding
       poll was ever captured. The array form is what this file uses.

       ------------------------------------------------------------
       CFP_BRACKET — the projected 12-team field
       ------------------------------------------------------------
         const CFP_BRACKET = [
           {
             week: 10,
             projected: true,
             seeds: [
               { seed: 1,  team: "Ohio State", record: "8-0", auto: true },
               ...
               { seed: 12, team: "USF",        record: "8-0", auto: true },
             ],
             // optional — see BOWL NAMES below:
             bowls: { qf: ["Cotton Bowl", "Rose Bowl", "Fiesta Bowl", "Peach Bowl"],
                      sf: ["Orange Bowl", "Sugar Bowl"],
                      nc: "National Championship",
                      site: "Las Vegas, NV" },
           },
         ];

       TWELVE SEEDS AND NOTHING ELSE. The matchups are NOT transcribed,
       because the 12-team bracket's structure is fixed: seeds 1-4 get a
       first-round bye, and the first round is 5v12, 6v11, 7v10, 8v9,
       feeding 4, 3, 2 and 1 respectively. Deriving the lines from the
       seed list means the site cannot draw a bracket that disagrees with
       itself — there is no second copy of the pairings to fall out of
       sync. Read the seeds off the screenshot; the shape is arithmetic.

       `auto: true` is the asterisk in-game — a conference champion
       holding an automatic bid. It is display-only; it does not move a
       team's seed, because the game has already done that.

       `projected: true` means the field is a forecast, which it is every
       week from 10 through the conference championships. Set it false
       (tools/cfp.js --final) on the bracket entered after the CCGs, when
       the field is settled and the games are actually being played.

       BOWL NAMES are entered ONCE and merge forward key by key. `qf` is
       four names top to bottom; `sf` is two; `r1` is four if the game
       names the first-round sites; `nc` is the title game; `site` is
       where it's played.

       Merging matters because the assignments arrive at different times:
       the quarterfinal bowls are named on the week-10 bracket, the
       semifinal bowls only later. Taking the newest bracket's `bowls`
       whole would mean the week the semifinals appear is the week the
       quarterfinals go blank. So each name is entered on the first
       bracket that knows it and stays from then on — a fact about the
       season, not about the week.

       All of it is optional; the site renders the rounds generically
       without any of it.

       ------------------------------------------------------------
       HOW TO ADD A WEEK
       ------------------------------------------------------------
       Screenshot the in-game CFP Top 25 and the projected bracket, then:

         node tools/cfp.js --league main --week 10 \
           --poll poll.txt --bracket bracket.txt

       Do not hand-edit this file. The script counts to 25, counts to 12,
       catches a doubled rank or seed, checks every team name against the
       league's data, and refuses to overwrite a week that is already
       public history. See tools/README.md.

       WHEN IT APPEARS ON THE SITE
       Same reveal rule as the AP poll: the site shows the CFP week that
       SEASON.currentWeek has actually reached. A week entered ahead of
       the advance sits here invisible until the season catches up, and
       the main dynasty's advance to week 10+ is gated on this file
       having that week.
       ============================================================ */
    const CFP_POLL = [
      {
        week: 10,
        teams: [
          { rank: 1, team: "Ole Miss", record: "8-0" },
          { rank: 2, team: "Georgia", record: "8-1" },
          { rank: 3, team: "Oregon", record: "7-1" },
          { rank: 4, team: "Tennessee", record: "8-1" },
          { rank: 5, team: "Wisconsin", record: "8-0" },
          { rank: 6, team: "Texas A&M", record: "7-2" },
          { rank: 7, team: "Miami", record: "8-1" },
          { rank: 8, team: "Ohio State", record: "6-2" },
          { rank: 9, team: "South Carolina", record: "7-1" },
          { rank: 10, team: "Notre Dame", record: "5-3" },
          { rank: 11, team: "Michigan", record: "6-2" },
          { rank: 12, team: "Texas Tech", record: "6-2" },
          { rank: 13, team: "California", record: "8-1" },
          { rank: 14, team: "Maryland", record: "8-0" },
          { rank: 15, team: "Mississippi St", record: "8-0" },
          { rank: 16, team: "Michigan State", record: "7-1" },
          { rank: 17, team: "USC", record: "6-2" },
          { rank: 18, team: "LSU", record: "6-3" },
          { rank: 19, team: "BYU", record: "6-2" },
          { rank: 20, team: "Pittsburgh", record: "8-1" },
          { rank: 21, team: "Texas", record: "5-3" },
          { rank: 22, team: "UCF", record: "7-1" },
          { rank: 23, team: "Kentucky", record: "6-2" },
          { rank: 24, team: "Vanderbilt", record: "7-1" },
          { rank: 25, team: "Arizona", record: "6-2" },
        ],
      },
      {
        week: 11,
        teams: [
          { rank: 1, team: "Georgia", record: "9-1" },
          { rank: 2, team: "Wisconsin", record: "9-0" },
          { rank: 3, team: "Ohio State", record: "7-2" },
          { rank: 4, team: "Ole Miss", record: "8-1" },
          { rank: 5, team: "Miami", record: "8-1" },
          { rank: 6, team: "Texas A&M", record: "7-2" },
          { rank: 7, team: "Oregon", record: "7-2" },
          { rank: 8, team: "South Carolina", record: "8-1" },
          { rank: 9, team: "Maryland", record: "9-0" },
          { rank: 10, team: "Michigan", record: "7-2" },
          { rank: 11, team: "California", record: "8-1" },
          { rank: 12, team: "Texas Tech", record: "7-2" },
          { rank: 13, team: "Mississippi St", record: "9-0" },
          { rank: 14, team: "USC", record: "7-2" },
          { rank: 15, team: "Tennessee", record: "8-2" },
          { rank: 16, team: "BYU", record: "7-2" },
          { rank: 17, team: "LSU", record: "7-3" },
          { rank: 18, team: "Pittsburgh", record: "8-1" },
          { rank: 19, team: "UCF", record: "8-1" },
          { rank: 20, team: "Texas", record: "6-3" },
          { rank: 21, team: "Arizona", record: "7-2" },
          { rank: 22, team: "Michigan State", record: "7-2" },
          { rank: 23, team: "Colorado", record: "7-2" },
          { rank: 24, team: "Oklahoma", record: "6-3" },
          { rank: 25, team: "Penn State", record: "6-3" },
        ],
      },
      {
        week: 12,
        teams: [
          { rank: 1, team: "Georgia", record: "9-1" },
          { rank: 2, team: "Ohio State", record: "8-2" },
          { rank: 3, team: "Oregon", record: "8-2" },
          { rank: 4, team: "Maryland", record: "10-0" },
          { rank: 5, team: "Wisconsin", record: "9-1" },
          { rank: 6, team: "California", record: "9-1" },
          { rank: 7, team: "South Carolina", record: "9-1" },
          { rank: 8, team: "Texas Tech", record: "8-2" },
          { rank: 9, team: "USC", record: "8-2" },
          { rank: 10, team: "Texas A&M", record: "7-3" },
          { rank: 11, team: "Tennessee", record: "9-2" },
          { rank: 12, team: "Ole Miss", record: "8-2" },
          { rank: 13, team: "BYU", record: "8-2" },
          { rank: 14, team: "Pittsburgh", record: "9-1" },
          { rank: 15, team: "Miami", record: "8-2" },
          { rank: 16, team: "UCF", record: "9-1" },
          { rank: 17, team: "Texas", record: "7-3" },
          { rank: 18, team: "Colorado", record: "8-2" },
          { rank: 19, team: "Oklahoma", record: "7-3" },
          { rank: 20, team: "Missouri", record: "8-2" },
          { rank: 21, team: "Mississippi St", record: "9-1" },
          { rank: 22, team: "Michigan", record: "7-3" },
          { rank: 23, team: "James Madison", record: "7-3" },
          { rank: 24, team: "Virginia Tech", record: "8-2" },
          { rank: 25, team: "Vanderbilt", record: "8-2" },
        ],
      },
      {
        week: 13,
        teams: [
          { rank: 1, team: "Georgia", record: "10-1" },
          { rank: 2, team: "Maryland", record: "11-0" },
          { rank: 3, team: "Ohio State", record: "9-2" },
          { rank: 4, team: "Oregon", record: "9-2" },
          { rank: 5, team: "Wisconsin", record: "10-1" },
          { rank: 6, team: "California", record: "10-1" },
          { rank: 7, team: "Tennessee", record: "9-2" },
          { rank: 8, team: "South Carolina", record: "10-1" },
          { rank: 9, team: "Pittsburgh", record: "10-1" },
          { rank: 10, team: "BYU", record: "9-2" },
          { rank: 11, team: "UCF", record: "10-1" },
          { rank: 12, team: "Oklahoma", record: "8-3" },
          { rank: 13, team: "Missouri", record: "9-2" },
          { rank: 14, team: "Colorado", record: "9-2" },
          { rank: 15, team: "Mississippi St", record: "10-1" },
          { rank: 16, team: "Michigan", record: "8-3" },
          { rank: 17, team: "Virginia Tech", record: "9-2" },
          { rank: 18, team: "Texas Tech", record: "8-3" },
          { rank: 19, team: "USC", record: "8-3" },
          { rank: 20, team: "Vanderbilt", record: "9-2" },
          { rank: 21, team: "Ole Miss", record: "8-3" },
          { rank: 22, team: "Kansas State", record: "9-2" },
          { rank: 23, team: "Notre Dame", record: "7-4" },
          { rank: 24, team: "Baylor", record: "8-3" },
          { rank: 25, team: "Miami", record: "8-3" },
        ],
      },
      {
        week: 14,
        teams: [
          { rank: 1, team: "Georgia", record: "11-1" },
          { rank: 2, team: "Maryland", record: "12-0" },
          { rank: 3, team: "Wisconsin", record: "11-1" },
          { rank: 4, team: "Oregon", record: "10-2" },
          { rank: 5, team: "Pittsburgh", record: "11-1" },
          { rank: 6, team: "South Carolina", record: "11-1" },
          { rank: 7, team: "UCF", record: "11-1" },
          { rank: 8, team: "BYU", record: "10-2" },
          { rank: 9, team: "Oklahoma", record: "9-3" },
          { rank: 10, team: "Missouri", record: "10-2" },
          { rank: 11, team: "Ohio State", record: "9-3" },
          { rank: 12, team: "Michigan", record: "9-3" },
          { rank: 13, team: "Tennessee", record: "9-3" },
          { rank: 14, team: "Virginia Tech", record: "10-2" },
          { rank: 15, team: "Vanderbilt", record: "10-2" },
          { rank: 16, team: "California", record: "10-2" },
          { rank: 17, team: "Ole Miss", record: "9-3" },
          { rank: 18, team: "Notre Dame", record: "8-4" },
          { rank: 19, team: "Miami", record: "9-3" },
          { rank: 20, team: "Baylor", record: "9-3" },
          { rank: 21, team: "North Dakota State", record: "8-4" },
          { rank: 22, team: "Mississippi State", record: "10-2" },
          { rank: 23, team: "Western Michigan", record: "11-1" },
          { rank: 24, team: "Florida State", record: "9-3" },
          { rank: 25, team: "Colorado", record: "9-3" },
        ],
      },
      {
        week: 15,
        teams: [
          { rank: 1, team: "Maryland", record: "13-0" },
          { rank: 2, team: "Pittsburgh", record: "12-1" },
          { rank: 3, team: "Oregon", record: "10-2" },
          { rank: 4, team: "Georgia", record: "11-2" },
          { rank: 5, team: "Wisconsin", record: "11-2" },
          { rank: 6, team: "BYU", record: "11-2" },
          { rank: 7, team: "South Carolina", record: "12-1" },
          { rank: 8, team: "Oklahoma", record: "9-3" },
          { rank: 9, team: "Missouri", record: "11-2" },
          { rank: 10, team: "UCF", record: "11-2" },
          { rank: 11, team: "Michigan", record: "9-3" },
          { rank: 12, team: "Tennessee", record: "10-3" },
          { rank: 13, team: "Ohio State", record: "9-3" },
          { rank: 14, team: "Vanderbilt", record: "11-2" },
          { rank: 15, team: "California", record: "10-2" },
          { rank: 16, team: "Ole Miss", record: "9-3" },
          { rank: 17, team: "Virginia Tech", record: "10-3" },
          { rank: 18, team: "Notre Dame", record: "8-4" },
          { rank: 19, team: "Miami", record: "9-3" },
          { rank: 20, team: "Baylor", record: "9-3" },
          { rank: 21, team: "North Dakota State", record: "8-4" },
          { rank: 22, team: "Western Michigan", record: "12-1" },
          { rank: 23, team: "Colorado", record: "9-3" },
          { rank: 24, team: "Mississippi State", record: "10-3" },
          { rank: 25, team: "Florida State", record: "9-3" },
        ],
      },
    ];

    const CFP_BRACKET = [
      {
        week: 10,
        projected: true,
        seeds: [
          { seed:  1, team: "Ole Miss", record: "8-0", auto: true },
          { seed:  2, team: "Georgia", record: "8-1" },
          { seed:  3, team: "Oregon", record: "7-1" },
          { seed:  4, team: "Tennessee", record: "8-1" },
          { seed:  5, team: "Wisconsin", record: "8-0" },
          { seed:  6, team: "Texas A&M", record: "7-2" },
          { seed:  7, team: "Miami", record: "8-1", auto: true },
          { seed:  8, team: "Ohio State", record: "6-2" },
          { seed:  9, team: "South Carolina", record: "7-1", auto: true },
          { seed: 10, team: "Notre Dame", record: "5-3", auto: true },
          { seed: 11, team: "Maryland", record: "8-0", auto: true },
          { seed: 12, team: "Colorado", record: "6-2", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Peach Bowl", "Rose Bowl", "Fiesta Bowl"],
          site: "Las Vegas, NV",
        },
      },
      {
        week: 11,
        projected: true,
        seeds: [
          { seed:  1, team: "Georgia", record: "9-1", auto: true },
          { seed:  2, team: "Wisconsin", record: "9-0", auto: true },
          { seed:  3, team: "Ohio State", record: "7-2" },
          { seed:  4, team: "Ole Miss", record: "8-1" },
          { seed:  5, team: "Miami", record: "8-1", auto: true },
          { seed:  6, team: "Texas A&M", record: "7-2" },
          { seed:  7, team: "Oregon", record: "7-2" },
          { seed:  8, team: "South Carolina", record: "8-1", auto: true },
          { seed:  9, team: "Maryland", record: "9-0", auto: true },
          { seed: 10, team: "Michigan", record: "7-2" },
          { seed: 11, team: "California", record: "8-1" },
          { seed: 12, team: "Texas Tech", record: "7-2", auto: true },
        ],
      },
      {
        week: 12,
        projected: true,
        seeds: [
          { seed:  1, team: "Georgia", record: "9-1", auto: true },
          { seed:  2, team: "Ohio State", record: "8-2" },
          { seed:  3, team: "Oregon", record: "8-2" },
          { seed:  4, team: "Maryland", record: "10-0", auto: true },
          { seed:  5, team: "Wisconsin", record: "9-1" },
          { seed:  6, team: "California", record: "9-1", auto: true },
          { seed:  7, team: "South Carolina", record: "9-1", auto: true },
          { seed:  8, team: "Texas Tech", record: "8-2", auto: true },
          { seed:  9, team: "USC", record: "8-2" },
          { seed: 10, team: "Texas A&M", record: "7-3" },
          { seed: 11, team: "Tennessee", record: "9-2" },
          { seed: 12, team: "Ole Miss", record: "8-2" },
        ],
      },
      {
        week: 13,
        projected: true,
        seeds: [
          { seed:  1, team: "Georgia", record: "10-1", auto: true },
          { seed:  2, team: "Maryland", record: "11-0", auto: true },
          { seed:  3, team: "Ohio State", record: "9-2" },
          { seed:  4, team: "Oregon", record: "9-2" },
          { seed:  5, team: "Wisconsin", record: "10-1" },
          { seed:  6, team: "California", record: "10-1", auto: true },
          { seed:  7, team: "Tennessee", record: "9-2" },
          { seed:  8, team: "South Carolina", record: "10-1", auto: true },
          { seed:  9, team: "Pittsburgh", record: "10-1" },
          { seed: 10, team: "BYU", record: "9-2" },
          { seed: 11, team: "UCF", record: "10-1" },
          { seed: 12, team: "Colorado", record: "9-2", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Peach Bowl", "Fiesta Bowl", "Rose Bowl"],
        },
      },
      {
        week: 14,
        projected: true,
        seeds: [
          { seed:  1, team: "Georgia", record: "11-1", auto: true },
          { seed:  2, team: "Maryland", record: "12-0", auto: true },
          { seed:  3, team: "Wisconsin", record: "11-1" },
          { seed:  4, team: "Oregon", record: "10-2" },
          { seed:  5, team: "Pittsburgh", record: "11-1" },
          { seed:  6, team: "South Carolina", record: "11-1", auto: true },
          { seed:  7, team: "UCF", record: "11-1", auto: true },
          { seed:  8, team: "BYU", record: "10-2" },
          { seed:  9, team: "Oklahoma", record: "9-3" },
          { seed: 10, team: "Missouri", record: "10-2" },
          { seed: 11, team: "Ohio State", record: "9-3" },
          { seed: 12, team: "Virginia Tech", record: "10-2", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Peach Bowl", "Fiesta Bowl", "Rose Bowl"],
          site: "Las Vegas, NV",
        },
      },
      {
        week: 15,
        projected: false,
        seeds: [
          { seed:  1, team: "Maryland", record: "13-0", auto: true },
          { seed:  2, team: "Pittsburgh", record: "12-1", auto: true },
          { seed:  3, team: "Oregon", record: "10-2" },
          { seed:  4, team: "Georgia", record: "11-2" },
          { seed:  5, team: "Wisconsin", record: "11-2" },
          { seed:  6, team: "BYU", record: "11-2", auto: true },
          { seed:  7, team: "South Carolina", record: "12-1", auto: true },
          { seed:  8, team: "Oklahoma", record: "9-3" },
          { seed:  9, team: "Missouri", record: "11-2" },
          { seed: 10, team: "UCF", record: "11-2" },
          { seed: 11, team: "Michigan", record: "9-3" },
          { seed: 12, team: "Tennessee", record: "10-3", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Rose Bowl", "Fiesta Bowl", "Peach Bowl"],
          site: "Las Vegas, NV",
        },
      },
    ];


    /* ---- postseason-data.js ---- */
    /* ============================================================
       POSTSEASON — conference championships, the CFP, and bowls
       ------------------------------------------------------------
       Everything played after the regular season. Format and rationale
       are documented in full at buildPostseason() in week-core.js and in
       docs/seasons-and-postseason.md; the short version is below.

         const POSTSEASON = {
           rounds: [
             { id: "ccg", label: "Conference Championships", games: [
               { home: "Georgia", away: "Texas", title: "SEC Championship",
                 neutral: true, stadium: "Mercedes-Benz Stadium",
                 homeScore: 31, awayScore: 24 },
             ]},
             { id: "cfp-r1", label: "CFP First Round",       games: [ ... ] },
             { id: "cfp-qf", label: "CFP Quarterfinal",      games: [ ... ] },
             { id: "cfp-sf", label: "CFP Semifinal",         games: [ ... ] },
             { id: "cfp-nc", label: "National Championship", games: [ ... ] },
             { id: "bowl",   label: "Bowl Games",            games: [ ... ] },
           ],
         };

       ONE ROW PER GAME, unlike the regular season, which stores a game
       twice — once on each team's week list. That redundancy is a
       liability for a handful of one-off neutral-site games: writing a
       game twice is how home/away disagreements and half-entered scores
       get in. One row per game removes the entire class of error.

       Rounds render in array order. There is no `order` field, so
       inserting a round means putting it in the right place.

       Omit both scores for a game that hasn't been played.

       THE FOUR cfp-* IDS ARE LOAD-BEARING. The CFP bracket on the Top 25
       tab advances its slots by looking for a played game between two
       known teams inside `cfp-r1`, `cfp-qf`, `cfp-sf` and `cfp-nc`, in
       that order. Rename one and the bracket quietly stops filling in
       past that round — it won't error, it will just show the rest of
       the field as undecided. The `label` beside each id is free text
       and safe to change.

       Empty is a valid state and the normal one until December.
       ============================================================ */
    const POSTSEASON = {
      rounds: [
        { id: "ccg", label: "Conference Championships", games: [
          { home: "Georgia", away: "Tennessee", title: "SEC Championship", neutral: true },
        ]},
        { id: "cfp-r1", label: "CFP First Round", games: [
          { home: "Oklahoma", away: "Missouri", homeScore: 33, awayScore: 28 },
          { home: "BYU", away: "Michigan", homeScore: 12, awayScore: 41 },
        ]},
        { id: "cfp-qf", label: "CFP Quarterfinals", games: [
          { home: "Maryland", away: "Oklahoma", neutral: true, homeScore: 24, awayScore: 21 },
          { home: "Oregon", away: "Michigan", neutral: true, homeScore: 27, awayScore: 24 },
        ]},
      ],
    };


    /* The same shape script.js assembles for the live season, so
       computeRankings / computeH2H / computeAchievements can't tell
       an archived season from the current one. */
    return {
      SEASON: typeof SEASON !== "undefined" ? SEASON : {},
      COACHES: typeof COACHES !== "undefined" ? COACHES : [],
      ALIASES: typeof SCHEDULE_TEAM_ALIASES !== "undefined" ? SCHEDULE_TEAM_ALIASES : {},
      TEAM_SCHEDULES: typeof TEAM_SCHEDULES !== "undefined" ? TEAM_SCHEDULES : [],
      TOP25: typeof TOP25 !== "undefined" ? TOP25 : [],
      POSTSEASON: typeof POSTSEASON !== "undefined" ? POSTSEASON : null,
      CFP_POLL: typeof CFP_POLL !== "undefined" ? CFP_POLL : null,
      CFP_BRACKET: typeof CFP_BRACKET !== "undefined" ? CFP_BRACKET : null,
    };
  })();

  /* THE FOLDER NAME WINS over the file's own SEASON.year — the same
     tiebreak loadCareer() applies, for the same reason: the folder is
     the thing a human can see and sort. */
  season.SEASON = Object.assign({}, season.SEASON, { year: 2026 });

  /* Oldest first. Script tags run in document order and each archive
     pushes as it loads, so index.html listing the years in order is
     what keeps CAREER sorted — computeRankings applies throughWeek to
     the LAST entry only, so a reversed list would cap the wrong
     season. */
  var all = (window.ARCHIVED_SEASONS = window.ARCHIVED_SEASONS || []);
  all.push(season);
})();
