/* ============================================================
   SCHEDULE DATA — transcribed from in-game "Custom Schedule"
   screenshots (2 per team, weeks 0-8 and 7-15, overlap on
   weeks 7-8 deduped by hand when this file was built).

   Only teams whose coach has shared a screenshot appear here.
   As more coaches send schedules, add a new entry to
   TEAM_SCHEDULES following the same shape — the site picks it
   up automatically in both the Weekly and By Team views.

   Each week entry:
     { week, opponent, location, stadium }   — location is
       "vs" (home) or "at" (away)
     { week, note }                          — bye / Army-Navy /
       conference championship weeks with no fixed opponent yet

   SCORES: once a week's games are final, add teamScore and
   opponentScore to that entry (that TEAM's own perspective —
   teamScore is this team's points, opponentScore is the other
   team's points, regardless of home/away). Do this on BOTH teams'
   entries for a league game so it shows correctly on both coaches'
   schedules, e.g.:
     { week: 4, opponent: "Clemson", location: "vs", stadium: "...",
       teamScore: 27, opponentScore: 24 }
   The site converts this into home/away scores automatically and
   marks the game "Final" everywhere it appears (Home preview,
   Schedule > Weekly, Schedule > By Team).

   CURRENT WEEK: script.js has a SEASON.currentWeek value (starts
   as "PRESEASON") that controls the Home tab. Bump it to a week
   number once that week actually kicks off in-game.
   ============================================================ */
const TEAM_SCHEDULES = [
  {
    team: "California",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "UCLA", location: "vs", stadium: "California Memorial Stadium", teamScore: 22, opponentScore: 9 },
      { week: 2, opponent: "Syracuse", location: "at", stadium: "JMA Wireless Dome" },
      { week: 3, opponent: "FCS West", location: "vs", stadium: "California Memorial Stadium" },
      { week: 4, opponent: "Clemson", location: "vs", stadium: "California Memorial Stadium" },
      { week: 5, opponent: "UNLV", location: "at", stadium: "Allegiant Stadium" },
      { week: 6, opponent: "Virginia Tech", location: "vs", stadium: "California Memorial Stadium" },
      { week: 7, opponent: "Wake Forest", location: "vs", stadium: "California Memorial Stadium" },
      { week: 8, opponent: "SMU", location: "at", stadium: "Gerald J. Ford Stadium" },
      { week: 9, opponent: "NC State", location: "at", stadium: "Carter-Finley Stadium" },
      { week: 10, note: "BYE" },
      { week: 11, opponent: "Virginia", location: "at", stadium: "Scott Stadium" },
      { week: 12, opponent: "Stanford", location: "vs", stadium: "California Memorial Stadium" },
      { week: 13, opponent: "Pittsburgh", location: "vs", stadium: "California Memorial Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "TCU",
    conference: "Big 12",
    weeks: [
      { week: 0, opponent: "North Carolina", location: "vs", stadium: "Dublin Stadium", teamScore: 27, opponentScore: 17 },
      { week: 1, note: "BYE" },
      { week: 2, opponent: "FCS Midwest", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 3, opponent: "Arkansas State", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 4, opponent: "UCF", location: "at", stadium: "Acrisure Bounce House" },
      { week: 5, opponent: "BYU", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "Baylor", location: "at", stadium: "McLane Stadium" },
      { week: 8, opponent: "West Virginia", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 9, opponent: "Kansas", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 10, opponent: "Arizona", location: "at", stadium: "Casino Del Sol Stadium" },
      { week: 11, opponent: "Kansas State", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 12, opponent: "Utah", location: "vs", stadium: "Amon G. Carter Stadium" },
      { week: 13, opponent: "Texas Tech", location: "at", stadium: "Jones Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big 12 Championship", stadium: "AT&T Stadium" },
    ],
  },
  {
    team: "Clemson",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "LSU", location: "at", stadium: "Tiger Stadium", teamScore: 21, opponentScore: 37 },
      { week: 2, opponent: "Ga Southern", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 3, opponent: "North Carolina", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 4, opponent: "California", location: "at", stadium: "California Memorial Stadium" },
      { week: 5, opponent: "Miami", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "FCS Southeast", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 8, opponent: "Virginia Tech", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 9, opponent: "Florida State", location: "at", stadium: "Doak Campbell Stadium" },
      { week: 10, opponent: "Syracuse", location: "at", stadium: "JMA Wireless Dome" },
      { week: 11, opponent: "Georgia Tech", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 12, opponent: "Duke", location: "at", stadium: "Wallace Wade Stadium" },
      { week: 13, opponent: "South Carolina", location: "vs", stadium: "Clemson Memorial Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "Florida",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "FLA Atlantic", location: "vs", stadium: "Ben Hill Griffin Stadium", teamScore: 41, opponentScore: 10 },
      { week: 2, opponent: "FCS Southeast", location: "vs", stadium: "Ben Hill Griffin Stadium" },
      { week: 3, opponent: "Auburn", location: "at", stadium: "Jordan-Hare Stadium" },
      { week: 4, opponent: "Ole Miss", location: "vs", stadium: "Ben Hill Griffin Stadium" },
      { week: 5, opponent: "Missouri", location: "at", stadium: "Faurot Field at Memorial Stadium" },
      { week: 6, opponent: "South Carolina", location: "vs", stadium: "Ben Hill Griffin Stadium" },
      { week: 7, opponent: "Texas", location: "at", stadium: "Texas Memorial Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Georgia", location: "at", stadium: "Mercedes-Benz Stadium" },
      { week: 10, opponent: "Oklahoma", location: "vs", stadium: "Ben Hill Griffin Stadium" },
      { week: 11, opponent: "Kentucky", location: "at", stadium: "Kroger Field" },
      { week: 12, opponent: "Vanderbilt", location: "vs", stadium: "Ben Hill Griffin Stadium" },
      { week: 13, opponent: "Florida State", location: "at", stadium: "Doak Campbell Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Oregon",
    conference: "Big Ten",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Boise State", location: "vs", stadium: "Autzen Stadium", teamScore: 42, opponentScore: 7 },
      { week: 2, opponent: "Oklahoma State", location: "at", stadium: "Boone Pickens Stadium" },
      { week: 3, opponent: "FCS Northwest", location: "vs", stadium: "Autzen Stadium" },
      { week: 4, opponent: "USC", location: "at", stadium: "Los Angeles Memorial Coliseum" },
      { week: 5, note: "BYE" },
      { week: 6, opponent: "UCLA", location: "vs", stadium: "Autzen Stadium" },
      { week: 7, opponent: "Nebraska", location: "vs", stadium: "Autzen Stadium" },
      { week: 8, opponent: "Illinois", location: "at", stadium: "Gies Memorial Stadium" },
      { week: 9, opponent: "Northwestern", location: "vs", stadium: "Autzen Stadium" },
      { week: 10, opponent: "Ohio State", location: "at", stadium: "Ohio Stadium" },
      { week: 11, opponent: "Michigan", location: "vs", stadium: "Autzen Stadium" },
      { week: 12, opponent: "Michigan State", location: "at", stadium: "Spartan Stadium" },
      { week: 13, opponent: "Washington", location: "vs", stadium: "Autzen Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "Florida State",
    conference: "ACC",
    weeks: [
      { week: 0, opponent: "New Mexico St.", location: "vs", stadium: "Doak Campbell Stadium", teamScore: 49, opponentScore: 37 },
      { week: 1, opponent: "SMU", location: "vs", stadium: "Doak Campbell Stadium", teamScore: 21, opponentScore: 28 },
      { week: 2, note: "BYE" },
      { week: 3, opponent: "Alabama", location: "at", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 4, opponent: "FCS Southeast", location: "vs", stadium: "Doak Campbell Stadium" },
      { week: 5, opponent: "Virginia", location: "vs", stadium: "Doak Campbell Stadium" },
      { week: 6, opponent: "Louisville", location: "at", stadium: "L&N Stadium" },
      { week: 7, opponent: "Miami", location: "at", stadium: "Hard Rock Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Clemson", location: "vs", stadium: "Doak Campbell Stadium" },
      { week: 10, opponent: "Boston College", location: "at", stadium: "Alumni Stadium" },
      { week: 11, opponent: "Pittsburgh", location: "at", stadium: "Acrisure Stadium" },
      { week: 12, opponent: "NC State", location: "vs", stadium: "Doak Campbell Stadium" },
      { week: 13, opponent: "Florida", location: "vs", stadium: "Doak Campbell Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "SMU",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Florida State", location: "at", stadium: "Doak Campbell Stadium", teamScore: 28, opponentScore: 21 },
      { week: 2, opponent: "FCS Midwest", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 3, opponent: "Louisville", location: "at", stadium: "L&N Stadium" },
      { week: 4, opponent: "Missouri State", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 5, opponent: "Boston College", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "Virginia", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 8, opponent: "California", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 9, opponent: "Syracuse", location: "at", stadium: "JMA Wireless Dome" },
      { week: 10, opponent: "Virginia Tech", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 11, opponent: "Wake Forest", location: "vs", stadium: "Gerald J. Ford Stadium" },
      { week: 12, opponent: "Notre Dame", location: "at", stadium: "Notre Dame Stadium" },
      { week: 13, opponent: "Stanford", location: "at", stadium: "Stanford Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "Washington",
    conference: "Big Ten",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Washington St.", location: "vs", stadium: "Husky Stadium" },
      { week: 2, opponent: "Utah State", location: "vs", stadium: "Husky Stadium" },
      { week: 3, opponent: "FCS Northwest", location: "vs", stadium: "Husky Stadium" },
      { week: 4, opponent: "Minnesota", location: "vs", stadium: "Husky Stadium" },
      { week: 5, opponent: "USC", location: "at", stadium: "Los Angeles Memorial Coliseum" },
      { week: 6, opponent: "Iowa", location: "vs", stadium: "Husky Stadium" },
      { week: 7, opponent: "Purdue", location: "at", stadium: "Ross-Ade Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Nebraska", location: "at", stadium: "Memorial Stadium" },
      { week: 10, opponent: "Penn State", location: "vs", stadium: "Husky Stadium" },
      { week: 11, opponent: "Michigan State", location: "at", stadium: "Spartan Stadium" },
      { week: 12, opponent: "Indiana", location: "vs", stadium: "Husky Stadium" },
      { week: 13, opponent: "Oregon", location: "at", stadium: "Autzen Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "South Carolina",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Kent State", location: "vs", stadium: "Williams-Brice Stadium", teamScore: 52, opponentScore: 15 },
      { week: 2, opponent: "FCS Southeast", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 3, opponent: "Mississippi St", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 4, opponent: "Alabama", location: "at", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 5, opponent: "Kentucky", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 6, opponent: "Florida", location: "at", stadium: "Ben Hill Griffin Stadium" },
      { week: 7, note: "BYE" },
      { week: 8, opponent: "Tennessee", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 9, opponent: "Oklahoma", location: "at", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 10, opponent: "Texas A&M", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 11, opponent: "Arkansas", location: "at", stadium: "DW Reynolds Razorback Stadium" },
      { week: 12, opponent: "Georgia", location: "vs", stadium: "Williams-Brice Stadium" },
      { week: 13, opponent: "Clemson", location: "at", stadium: "Clemson Memorial Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Ohio State",
    conference: "Big Ten",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Ball State", location: "vs", stadium: "Ohio Stadium", teamScore: 50, opponentScore: 10 },
      { week: 2, opponent: "Texas", location: "at", stadium: "Texas Memorial Stadium" },
      { week: 3, opponent: "Kent State", location: "vs", stadium: "Ohio Stadium" },
      { week: 4, opponent: "Illinois", location: "vs", stadium: "Ohio Stadium" },
      { week: 5, opponent: "Iowa", location: "at", stadium: "Kinnick Stadium" },
      { week: 6, opponent: "Maryland", location: "vs", stadium: "Ohio Stadium" },
      { week: 7, opponent: "Indiana", location: "at", stadium: "Memorial Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "USC", location: "at", stadium: "Los Angeles Memorial Coliseum" },
      { week: 10, opponent: "Oregon", location: "vs", stadium: "Ohio Stadium" },
      { week: 11, opponent: "Northwestern", location: "vs", stadium: "Ohio Stadium" },
      { week: 12, opponent: "Nebraska", location: "at", stadium: "Memorial Stadium" },
      { week: 13, opponent: "Michigan", location: "vs", stadium: "Ohio Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "Texas",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Texas State", location: "vs", stadium: "Texas Memorial Stadium", teamScore: 51, opponentScore: 7 },
      { week: 2, opponent: "Ohio State", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 3, opponent: "UTSA", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 4, opponent: "Tennessee", location: "at", stadium: "Neyland Stadium" },
      { week: 5, note: "BYE" },
      { week: 6, opponent: "Oklahoma", location: "at", stadium: "Cotton Bowl" },
      { week: 7, opponent: "Florida", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 8, opponent: "Ole Miss", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 9, opponent: "Mississippi St", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 10, opponent: "Missouri", location: "at", stadium: "Faurot Field at Memorial Stadium" },
      { week: 11, opponent: "LSU", location: "at", stadium: "Tiger Stadium" },
      { week: 12, opponent: "Arkansas", location: "vs", stadium: "Texas Memorial Stadium" },
      { week: 13, opponent: "Texas A&M", location: "at", stadium: "Kyle Field" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "USC",
    conference: "Big Ten",
    weeks: [
      { week: 0, opponent: "San Jose State", location: "vs", stadium: "Los Angeles Memorial Coliseum", teamScore: 38, opponentScore: 14 },
      { week: 1, opponent: "Fresno State", location: "vs", stadium: "Los Angeles Memorial Coliseum", teamScore: 41, opponentScore: 23 },
      { week: 2, opponent: "Louisiana", location: "vs", stadium: "Los Angeles Memorial Coliseum" },
      { week: 3, opponent: "Rutgers", location: "at", stadium: "SHI Stadium" },
      { week: 4, opponent: "Oregon", location: "vs", stadium: "Los Angeles Memorial Coliseum" },
      { week: 5, opponent: "Washington", location: "vs", stadium: "Los Angeles Memorial Coliseum" },
      { week: 6, opponent: "Penn State", location: "at", stadium: "West Shore Home Field at Beaver Stadium" },
      { week: 7, note: "BYE" },
      { week: 8, opponent: "Wisconsin", location: "at", stadium: "Camp Randall Stadium" },
      { week: 9, opponent: "Ohio State", location: "vs", stadium: "Los Angeles Memorial Coliseum" },
      { week: 10, note: "BYE" },
      { week: 11, opponent: "Indiana", location: "at", stadium: "Memorial Stadium" },
      { week: 12, opponent: "Maryland", location: "vs", stadium: "Los Angeles Memorial Coliseum" },
      { week: 13, opponent: "UCLA", location: "at", stadium: "Rose Bowl Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "Georgia",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "FCS Southeast", location: "vs", stadium: "Sanford Stadium", teamScore: 37, opponentScore: 19 },
      { week: 2, opponent: "W. Kentucky", location: "vs", stadium: "Sanford Stadium" },
      { week: 3, opponent: "Arkansas", location: "at", stadium: "DW Reynolds Razorback Stadium" },
      { week: 4, opponent: "Oklahoma", location: "vs", stadium: "Sanford Stadium" },
      { week: 5, opponent: "Vanderbilt", location: "vs", stadium: "Sanford Stadium" },
      { week: 6, opponent: "Alabama", location: "at", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 7, opponent: "Auburn", location: "vs", stadium: "Sanford Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Florida", location: "vs", stadium: "Mercedes-Benz Stadium" },
      { week: 10, opponent: "Ole Miss", location: "at", stadium: "Vaught-Hemingway Stadium" },
      { week: 11, opponent: "Missouri", location: "vs", stadium: "Sanford Stadium" },
      { week: 12, opponent: "South Carolina", location: "at", stadium: "Williams-Brice Stadium" },
      { week: 13, opponent: "Georgia Tech", location: "vs", stadium: "Sanford Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Michigan",
    conference: "Big Ten",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "W. Michigan", location: "vs", stadium: "Michigan Stadium", teamScore: 42, opponentScore: 17 },
      { week: 2, opponent: "Oklahoma", location: "vs", stadium: "Michigan Stadium" },
      { week: 3, opponent: "UTEP", location: "vs", stadium: "Michigan Stadium" },
      { week: 4, opponent: "Iowa", location: "vs", stadium: "Michigan Stadium" },
      { week: 5, opponent: "Minnesota", location: "at", stadium: "Huntington Bank Stadium" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "Penn State", location: "vs", stadium: "Michigan Stadium" },
      { week: 8, opponent: "Indiana", location: "vs", stadium: "Michigan Stadium" },
      { week: 9, opponent: "Rutgers", location: "at", stadium: "SHI Stadium" },
      { week: 10, opponent: "Michigan State", location: "vs", stadium: "Michigan Stadium" },
      { week: 11, opponent: "Oregon", location: "at", stadium: "Autzen Stadium" },
      { week: 12, opponent: "UCLA", location: "vs", stadium: "Michigan Stadium" },
      { week: 13, opponent: "Ohio State", location: "at", stadium: "Ohio Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "West Virginia",
    conference: "Big 12",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Coastal Carolina", location: "vs", stadium: "Milan Puskar Stadium", teamScore: 55, opponentScore: 14 },
      { week: 2, opponent: "FCS East", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 3, opponent: "Virginia", location: "vs", stadium: "Bank of America Stadium" },
      { week: 4, opponent: "Oklahoma State", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 5, opponent: "Iowa State", location: "at", stadium: "Jack Trice Stadium" },
      { week: 6, opponent: "Arizona", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 7, opponent: "Cincinnati", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 8, opponent: "TCU", location: "at", stadium: "Amon G. Carter Stadium" },
      { week: 9, note: "BYE" },
      { week: 10, opponent: "Texas Tech", location: "at", stadium: "Jones Stadium" },
      { week: 11, opponent: "Kansas", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 12, opponent: "Houston", location: "vs", stadium: "Milan Puskar Stadium" },
      { week: 13, opponent: "Utah", location: "at", stadium: "Rice-Eccles Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big 12 Championship", stadium: "AT&T Stadium" },
    ],
  },
  {
    team: "Colorado",
    conference: "Big 12",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Georgia Tech", location: "at", stadium: "Bobby Dodd Stadium" },
      { week: 2, opponent: "FCS Midwest", location: "vs", stadium: "Folsom Field" },
      { week: 3, opponent: "Northwestern", location: "at", stadium: "Ryan Field" },
      { week: 4, opponent: "Baylor", location: "at", stadium: "McLane Stadium" },
      { week: 5, opponent: "Texas Tech", location: "vs", stadium: "Folsom Field" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "Utah", location: "vs", stadium: "Folsom Field" },
      { week: 8, opponent: "Oklahoma State", location: "at", stadium: "Boone Pickens Stadium" },
      { week: 9, opponent: "Kansas State", location: "vs", stadium: "Folsom Field" },
      { week: 10, opponent: "Arizona State", location: "at", stadium: "Mountain America Stadium" },
      { week: 11, opponent: "Houston", location: "vs", stadium: "Folsom Field" },
      { week: 12, opponent: "Cincinnati", location: "at", stadium: "Nippert Stadium" },
      { week: 13, opponent: "UCF", location: "vs", stadium: "Folsom Field" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big 12 Championship", stadium: "AT&T Stadium" },
    ],
  },
  {
    team: "Wake Forest",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Akron", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 2, opponent: "Purdue", location: "at", stadium: "Ross-Ade Stadium" },
      { week: 3, opponent: "Miami", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 4, opponent: "Louisville", location: "at", stadium: "L&N Stadium" },
      { week: 5, opponent: "Stanford", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 6, opponent: "NC State", location: "at", stadium: "Carter-Finley Stadium" },
      { week: 7, opponent: "California", location: "at", stadium: "California Memorial Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Virginia", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 10, opponent: "FCS Southeast", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 11, opponent: "SMU", location: "at", stadium: "Gerald J. Ford Stadium" },
      { week: 12, opponent: "Georgia Tech", location: "at", stadium: "Bobby Dodd Stadium" },
      { week: 13, opponent: "Duke", location: "vs", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "UCLA",
    conference: "Big Ten",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "California", location: "at", stadium: "California Memorial Stadium", teamScore: 9, opponentScore: 22 },
      { week: 2, opponent: "San Diego St.", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 3, opponent: "Purdue", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 4, opponent: "Maryland", location: "at", stadium: "SECU Stadium" },
      { week: 5, note: "BYE" },
      { week: 6, opponent: "Oregon", location: "at", stadium: "Autzen Stadium" },
      { week: 7, opponent: "Wisconsin", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 8, opponent: "Michigan State", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 9, opponent: "Nevada", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 10, opponent: "Minnesota", location: "at", stadium: "Huntington Bank Stadium" },
      { week: 11, opponent: "Illinois", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 12, opponent: "Michigan", location: "at", stadium: "Michigan Stadium" },
      { week: 13, opponent: "USC", location: "vs", stadium: "Rose Bowl Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "Big Ten Championship", stadium: "Lucas Oil Stadium" },
    ],
  },
  {
    team: "Miami",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Stanford", location: "at", stadium: "Stanford Stadium", teamScore: 30, opponentScore: 23 },
      { week: 2, opponent: "FCS Southeast", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 3, opponent: "Wake Forest", location: "at", stadium: "Allegacy Federal Credit Union Stadium" },
      { week: 4, opponent: "C. Michigan", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 5, opponent: "Clemson", location: "at", stadium: "Clemson Memorial Stadium" },
      { week: 6, note: "BYE" },
      { week: 7, opponent: "Florida State", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 8, opponent: "Pittsburgh", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 9, opponent: "North Carolina", location: "at", stadium: "Kenan Stadium" },
      { week: 10, opponent: "Notre Dame", location: "at", stadium: "Notre Dame Stadium" },
      { week: 11, opponent: "Duke", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 12, opponent: "Virginia Tech", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 13, opponent: "Boston College", location: "vs", stadium: "Hard Rock Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
  {
    team: "Notre Dame",
    conference: "Independent",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "Wisconsin", location: "vs", stadium: "Notre Dame Stadium", teamScore: 44, opponentScore: 14 },
      { week: 2, opponent: "Rice", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 3, opponent: "Michigan State", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 4, opponent: "Purdue", location: "at", stadium: "Ross-Ade Stadium" },
      { week: 5, opponent: "North Carolina", location: "at", stadium: "Kenan Stadium" },
      { week: 6, opponent: "Stanford", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 7, opponent: "BYU", location: "at", stadium: "LaVell Edwards Stadium" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Navy", location: "at", stadium: "Gillette Stadium" },
      { week: 10, opponent: "Miami", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 11, opponent: "Boston College", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 12, opponent: "SMU", location: "vs", stadium: "Notre Dame Stadium" },
      { week: 13, opponent: "Syracuse", location: "at", stadium: "JMA Wireless Dome" },
      { week: 14, note: "Army-Navy Week" },
      // Week 15 was not visible in the screenshots. Notre Dame is an
      // independent so it plays no conference championship - confirm
      // whether the game shows OPEN here and adjust if needed.
      { week: 15, note: "No conference championship (Independent)" },
    ],
  },
  {
    team: "Ole Miss",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      // Neutral site - listed "vs" in-game but played at Nissan Stadium
      // in Nashville, not Vaught-Hemingway.
      { week: 1, opponent: "Louisville", location: "vs", stadium: "Nissan Stadium", teamScore: 47, opponentScore: 17 },
      { week: 2, opponent: "Charlotte", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 3, opponent: "LSU", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 4, opponent: "Florida", location: "at", stadium: "Ben Hill Griffin Stadium" },
      { week: 5, note: "BYE" },
      { week: 6, opponent: "Vanderbilt", location: "at", stadium: "FirstBank Stadium" },
      { week: 7, opponent: "Missouri", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 8, opponent: "Texas", location: "at", stadium: "Texas Memorial Stadium" },
      { week: 9, opponent: "Auburn", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 10, opponent: "Georgia", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 11, opponent: "Oklahoma", location: "at", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 12, opponent: "FCS Southeast", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 13, opponent: "Mississippi St", location: "vs", stadium: "Vaught-Hemingway Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Oklahoma",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "UTEP", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 2, opponent: "Michigan", location: "at", stadium: "Michigan Stadium" },
      { week: 3, opponent: "New Mexico", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 4, opponent: "Georgia", location: "at", stadium: "Sanford Stadium" },
      { week: 5, note: "BYE" },
      // Red River rivalry - listed "vs" on Oklahoma's screen but played
      // at the neutral-site Cotton Bowl, which is what Texas's file says.
      { week: 6, opponent: "Texas", location: "vs", stadium: "Cotton Bowl" },
      { week: 7, opponent: "Kentucky", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 8, opponent: "Mississippi State", location: "at", stadium: "Davis Wade Stadium" },
      { week: 9, opponent: "South Carolina", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 10, opponent: "Florida", location: "at", stadium: "Ben Hill Griffin Stadium" },
      { week: 11, opponent: "Ole Miss", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 12, opponent: "Texas A&M", location: "vs", stadium: "Gaylord Family Oklahoma Memorial Stadium" },
      { week: 13, opponent: "Missouri", location: "at", stadium: "Faurot Field at Memorial Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Alabama",
    conference: "SEC",
    weeks: [
      { week: 0, note: "BYE" },
      { week: 1, opponent: "East Carolina", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium", teamScore: 70, opponentScore: 10 },
      { week: 2, opponent: "Kentucky", location: "at", stadium: "Kroger Field" },
      { week: 3, opponent: "Florida State", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 4, opponent: "South Carolina", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 5, opponent: "Mississippi State", location: "at", stadium: "Davis Wade Stadium" },
      { week: 6, opponent: "Georgia", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 7, opponent: "Tennessee", location: "at", stadium: "Neyland Stadium" },
      { week: 8, opponent: "Texas A&M", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 9, note: "BYE" },
      { week: 10, opponent: "LSU", location: "at", stadium: "Tiger Stadium" },
      { week: 11, opponent: "Vanderbilt", location: "at", stadium: "FirstBank Stadium" },
      { week: 12, opponent: "FCS Southeast", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 13, opponent: "Auburn", location: "vs", stadium: "Saban Field at Bryant-Denny Stadium" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "SEC Championship", stadium: "Mercedes-Benz Stadium" },
    ],
  },
  {
    team: "Louisville",
    conference: "ACC",
    weeks: [
      { week: 0, note: "BYE" },
      // Neutral site - listed "vs" on both teams' screens but played at
      // Nissan Stadium in Nashville, which matches Ole Miss's file.
      { week: 1, opponent: "Ole Miss", location: "vs", stadium: "Nissan Stadium" },
      { week: 2, opponent: "FCS Southeast", location: "vs", stadium: "L&N Stadium" },
      { week: 3, opponent: "SMU", location: "vs", stadium: "L&N Stadium" },
      { week: 4, opponent: "Wake Forest", location: "vs", stadium: "L&N Stadium" },
      { week: 5, opponent: "NC State", location: "at", stadium: "Carter-Finley Stadium" },
      { week: 6, opponent: "Florida State", location: "vs", stadium: "L&N Stadium" },
      { week: 7, opponent: "Syracuse", location: "at", stadium: "JMA Wireless Dome" },
      { week: 8, note: "BYE" },
      { week: 9, opponent: "Stanford", location: "vs", stadium: "L&N Stadium" },
      { week: 10, opponent: "Georgia Tech", location: "at", stadium: "Bobby Dodd Stadium" },
      { week: 11, opponent: "North Carolina", location: "at", stadium: "Kenan Stadium" },
      { week: 12, opponent: "Pittsburgh", location: "vs", stadium: "L&N Stadium" },
      { week: 13, opponent: "Kentucky", location: "at", stadium: "Kroger Field" },
      { week: 14, note: "Army-Navy Week" },
      { week: 15, note: "ACC Championship", stadium: "Bank of America Stadium" },
    ],
  },
];

/* Schedule-team-name -> roster-team-name, for the handful of cases
   where the in-game team name doesn't match what's in the sign-up
   sheet verbatim (e.g. "Cal" on the roster vs "California" in-game). */
const SCHEDULE_TEAM_ALIASES = {
  "California": "Cal",
  "Florida State": "FSU",
};
