/* ============================================================
   2026 — ARCHIVED SEASON, loaded by the site
   ------------------------------------------------------------
   GENERATED by tools/rollover.js. Don't hand-edit: it is the five
   data files beside it, wrapped so their top-level declarations
   become function-locals instead of page globals. Without that,
   this season's SEASON/COACHES/TEAM_SCHEDULES would collide with
   the live season's and the page would fail to start.

   Edit the files next to this one if a fact about 2026 is wrong,
   then regenerate. Better still: don't. This is history.
   ============================================================ */
(function () {
  "use strict";

  var season = (function () {
    /* ---- league-data.js ---- */
    /* ============================================================
       1-STAR DYNASTY — roster, season state, and power rankings
       ------------------------------------------------------------
       Same shape as every other league's league-data.js, with one
       addition: teams here are Team Builder originals, so they carry a
       local `logo` path instead of an ESPN CDN id. See the LOGOS note
       further down.
       ============================================================ */

    /* ------------------------------------------------------------
       SEASON STATE — manually advanced, never date-driven.

       Advanced off "PRESEASON" on 2026-07-22, when all eight team
       schedules were transcribed into schedule-data.js. Week 0 games
       haven't been played yet — only Patriot Tech, Wawa and Westeros
       have a week 0 opponent at all; the other five are on a bye.

       The advance deadline is the only real-world date on the site — a
       scheduling deadline for coaches, not part of season chronology.
       It's stored twice: nextAdvanceAt is the authored value and
       nextAdvance is the sentence generated from it, so neither is
       hand-edited. See the long note in main/league-data.js.

       THIS LEAGUE SETS A DAY, NOT A TIME. Writing the bare date
       "2026-08-12" rather than a full timestamp is what keeps the badge
       reading "Wednesday, August 12th" with no clock time attached, the
       way it always has. Internally the day still resolves to 10 PM
       Eastern so the advance-day heads-up has an instant to compare
       against — that just never reaches the site. Add a time here and
       the badge starts showing one.

       Set both to "" to hide the badge entirely.

       THE HOLD (2026-08-31). The bowls are played and the league is in
       the offseason: `currentWeek: "OFFSEASON"`, which seasonIndex()
       reads as week 19 — everything has happened — and both deadline
       fields cleared, because the nine in-game offseason steps are
       announced in Discord and the site has nothing to count down to.
       `statusLine` is free text and is the place a per-step line like
       "OFFSEASON \u00b7 SIGNING DAY" goes if it's wanted.

       The hold ends at Advance to Preseason on the admin page, which
       archives 2026 into 1star/seasons/2026/ and starts 2027. See
       docs/SCOPING-offseason-and-season-rollover.md.
       ------------------------------------------------------------ */
    const SEASON = {
      // In-game year for this season's data. See the long note in
      // main/league-data.js — it governs the seasons/<year>/ archive.
      year: 2026,

      currentWeek: "OFFSEASON",
      statusLine: "OFFSEASON",
      nextAdvanceAt: "",
      nextAdvance: "",
    };

    /* ------------------------------------------------------------
       LEAGUE IDENTITY
       ------------------------------------------------------------ */
    const LEAGUE_INFO = {
      name: "NCAA Legends",
      tag: "1-Star Dynasty",

      links: {
        discord: "",
        rules: "",
      },

      /* Every COACH team here is fictional and carries a local `logo`,
         which teamLogoSrc() checks before the CDN. But the schedules
         are full of real CPU opponents, so this must stay true or
         those marks all collapse to monograms. */
      useEspnLogos: true,
    };

    /* ------------------------------------------------------------
       COACHES — from the 1-star sign-up sheet, snapshot 2026-07-21,
       plus Scuba (Appalachian State), added 2026-07-27.

       The sheet's "SIM Sign Up" section is still TBD and would render
       as empty cards, so it's deliberately excluded until it firms up.

       LOGOS
         The eight original teams are Team Builder builds, so there's
         no ESPN id to hotlink. Each carries `logo`, a path relative to
         this folder, pointing at an optimised PNG in 1star/logos/.
         script.js prefers `logo` over `espnId` when both exist, and
         falls back to the monogram chip if the file 404s. Scuba's
         Appalachian State is a stock team and uses `espnId` instead —
         which works because useEspnLogos is true above.

         Source art was 9.6 MB across 8 files; these are resampled to
         400px max edge (0.74 MB total). Originals are NOT in the repo
         — keep them somewhere safe if you want to re-derive.

       COLORS were sampled from each logo by eye, not by histogram —
       an automated pass picked the White Walker's sword and the moose
       outline.

         New Glarus is pure black-and-white artwork, so there's no
         color in the logo to pull from. It's taken instead from the
         green banner on the team's in-game Team Schedule screen,
         which reads about #196441 mid-gradient. That's only 2.4:1 on
         --navy-panel, and --team is used as a text color in the
         league picker, not just as a border — so the hue is kept and
         the value lifted to #3E9B6B (4.9:1). Same green, legible on
         the dark theme.

         Heads up: this sits close to North Shore's #4FAE6E and both
         are MAC teams, so they land near each other on the roster
         grid. Known and accepted — the logos carry the identity.

       `replacing` records which stock team the build replaced. Not
       rendered anywhere — kept because it's easy to lose track of.
       ------------------------------------------------------------ */
    const COACHES = [
      { name: "BluBus",     team: "Dillon",                  conference: "Sun Belt", color: "#5990E3", twitch: "https://www.twitch.tv/blubusbandit", logo: "logos/dillon-panthers.png",            location: "Dillon, TX",      replacing: "Georgia Southern" },
      { name: "Alex",       team: "North Shore",             conference: "MAC",      color: "#4FAE6E", twitch: "https://www.twitch.tv/alexgators1", logo: "logos/north-shore-fighting-moose.png", location: "Duluth, MN",      replacing: "Akron" },
      { name: "Dway",       team: "Minneapolis",             conference: "MAC",      color: "#C3E63F", twitch: "https://www.twitch.tv/dwayinspired", logo: "logos/minneapolis-monsters.png",       location: "Minneapolis, MN", replacing: "Kent State" },
      { name: "Salzy",      team: "New Glarus",              conference: "MAC",      color: "#3E9B6B", twitch: "https://www.twitch.tv/salzy117", logo: "logos/new-glarus-spotted-cows.png",    location: "New Glarus, WI",  replacing: "Ball State" },
      { name: "Bl00dVayN3", team: "Westeros",                conference: "CUSA",     color: "#A8D5E8", twitch: "https://www.twitch.tv/bl00dvayn3", logo: "logos/westeros-white-walkers.png",     location: "Boise, ID",       replacing: "Western Kentucky" },
      { name: "Woody",      team: "Baldwin Wallace",         conference: "Sun Belt", color: "#F3CD49", twitch: "https://www.twitch.tv/mldwoody", logo: "logos/baldwin-wallace.png",            location: "Berea, OH",       replacing: "South Alabama" },
      { name: "Brian52682", team: "Patriot Tech",            conference: "CUSA",     color: "#DE4B5C", twitch: "https://www.twitch.tv/brian52682", logo: "logos/patriot-tech-minutemen.png",     location: "",                replacing: "Liberty" },
      { name: "Bayside",    team: "Wawa University",         conference: "CUSA",    color: "#EE4B3C", twitch: "https://www.twitch.tv/baysideblitz", logo: "logos/wawa-university.png",            location: "Media, PA",       replacing: "FIU" },

      /* Joined 2026-07-27, mid-season. The only stock team on this
         roster — Scuba took Appalachian State as-is rather than
         building an original, so there's no `logo` and no `replacing`;
         the ESPN id carries the mark like it does in the other two
         leagues. Color is the official App State gold, which reads
         cleanly on --navy-panel without lifting. */
      { name: "Scuba",      team: "Appalachian State",       conference: "Sun Belt", color: "#FFCC00", twitch: "https://www.twitch.tv/scuba2122", espnId: "2026",                               location: "Boone, NC" },
    ];

    /* ------------------------------------------------------------
       POWER RANKINGS

       Empty until the season starts and enough H2H (user vs. user)
       games are on the board. Shape:
         { week: 3, rank: 1, team: "Dillon", record: "3-0", score: 97.5 }
       ------------------------------------------------------------ */
    const RANKINGS = [];


    /* ---- schedule-data.js ---- */
    /* ============================================================
       1-STAR DYNASTY — SCHEDULE DATA
       ------------------------------------------------------------
       Transcribed from in-game "Team Schedule" screenshots, 2 per
       team (weeks 0-8 and weeks 8-16), overlap deduped by hand.
       Snapshot taken 2026-07-22, preseason. Appalachian State was
       added 2026-07-27 from a week 2 snapshot, so its first two rows
       already carry results while the other eight teams' do not.

       All 9 coaches are represented. Every user-vs-user matchup was
       cross-checked against BOTH coaches' screenshots and the
       home/away sides agree in all cases (10 league games total).

       WEEK MAPPING. The in-game table lists rows 0-14, then
       "Conf Champ", then 16. This file follows the convention the
       main and 3-star dynasties use and that script.js's weekLabel()
       expects:
           weeks 0-13   regular season games
           week 14      Army-Navy Week
           week 15      conference championship
           weeks 16-19  Bowl Weeks 1-4 (CFP rounds + bowls)

       THE POSTSEASON LIVES HERE TOO — weeks 15-19. A conference
       championship, a bowl or a CFP round that a COACHED team played is
       an ordinary row on that team's schedule, with three optional extra
       fields:

         neutral: true      no true home team. home/away still decide
                            which score is which; the row renders "VS" at
                            the named stadium rather than claiming "AT".
         title: "Rose Bowl" the game's own name. Replaces the week number
                            in the schedule row and the card footer.
         round: "cfp-qf"    the machine-readable round id. One of:
                            ccg, bowl-w1, bowl-w2,
                            cfp-r1, cfp-qf, cfp-sf, cfp-nc

       `round` IS LOAD-BEARING AND `title` IS NOT. Conference titles, CFP
       appearances and national championships on the roster cards are
       derived by matching `round`; a bowl game with a title and no round
       renders correctly and earns nothing. The round is never inferred
       from the title, because a sponsor renaming a bowl would silently
       stop counting it.

         { week: 17, opponent: "Miami", location: "vs", neutral: true,
           stadium: "AT&T Stadium", title: "Cotton Bowl", round: "cfp-qf",
           teamScore: 31, opponentScore: 24 }

       A game between two teams NOBODY coaches — most of the CFP bracket
       — has no coach's schedule to live on and goes in
       postseason-data.js instead.
       In-game week 14 and "Conf Champ" both read BYE for all eight
       teams right now; they're written as the labelled weeks anyway
       so the site renders them consistently with the other leagues.
       The trailing in-game row 16 (a post-CCG bye for everyone) is
       not carried over — nothing renders it.

       TEAM NAMES. The roster names in league-data.js are the short
       location-only names (no mascot) — "Baldwin Wallace", "North
       Shore", "Wawa University", "Westeros", "Patriot Tech",
       "Minneapolis", "New Glarus", "Dillon" — which is also close to
       what the in-game Team Schedule screen shows. Spell them exactly
       that way here so validateData() resolves them without aliases.
       Mascots live in the logo art, not the name.

       STADIUMS. The Team Schedule screen doesn't display venue, so
       stadium is intentionally omitted. script.js treats it as
       optional (renders an empty span). Can be filled in per entry
       later if it's wanted.

       SCORES. None yet — every row still shows a kickoff time rather
       than a result. When a game goes final, add teamScore /
       opponentScore from THAT team's own perspective. For a
       user-vs-user game, add it to BOTH teams' entries or it'll only
       show on one coach's schedule.

       NAME NOTES
         - "Miami University" (the Ohio RedHawks, MAC) appears on the
           Minneapolis and North Shore schedules. It is NOT "Miami"
           (the ACC Hurricanes). Don't collapse them.
         - FCS opponents are regional placeholders — FCS Southeast,
           FCS Midwest, FCS East — and are spelled as the game
           spells them.

       CONFERENCES match league-data.js: Sun Belt, MAC and CUSA. Each
       of these teams replaced a stock team in that league, so the
       alignment is stock; only the team identities are custom.
       ============================================================ */
    const TEAM_SCHEDULES = [
      /* -------------------------- SUN BELT -------------------------- */
      {
        team: "Baldwin Wallace",
        conference: "Sun Belt",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "FCS Southeast", location: "vs", teamScore: 38, opponentScore: 10 },
          { week: 2, opponent: "Tulane", location: "at", teamScore: 21, opponentScore: 31 },
          { week: 3, opponent: "Ohio", location: "vs", teamScore: 38, opponentScore: 30 },
          { week: 4, opponent: "North Shore", location: "at", teamScore: 34, opponentScore: 13 },
          { week: 5, opponent: "UL Monroe", location: "vs", teamScore: 20, opponentScore: 27 },
          { week: 6, opponent: "Arkansas State", location: "at", teamScore: 21, opponentScore: 20 },
          { week: 7, note: "BYE" },
          { week: 8, opponent: "Marshall", location: "at", teamScore: 14, opponentScore: 24 },
          { week: 9, opponent: "Louisiana Tech", location: "vs", teamScore: 49, opponentScore: 37 },
          { week: 10, opponent: "Louisiana", location: "at", teamScore: 24, opponentScore: 3 },
          { week: 11, opponent: "Troy", location: "vs", teamScore: 28, opponentScore: 21 },
          { week: 12, opponent: "Southern Mississippi", location: "at", teamScore: 34, opponentScore: 30 },
          { week: 13, opponent: "Appalachian State", location: "vs", teamScore: 9, opponentScore: 24, sim: true },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 17, opponent: "UAB", location: "at", neutral: true, title: "First Responder Bowl", round: "bowl-w2", teamScore: 49, opponentScore: 27 },
        ],
      },
      {
        /* Added 2026-07-27 from Scuba's two Team Schedule screenshots
           (weeks 0-8, weeks 8-16). Both league games check out against
           the other coach's transcription: Baldwin Wallace already had
           week 13 "vs Appalachian State" and Dillon week 9 "vs", and
           this schedule reads "at" for both. The in-game screen renders
           Baldwin Wallace as "BaldwinWallace" with no space; expanded
           here to the roster spelling per the TEAM NAMES note above. */
        team: "Appalachian State",
        conference: "Sun Belt",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "FCS Southeast", location: "vs", teamScore: 28, opponentScore: 7 },
          { week: 2, opponent: "East Carolina", location: "at", teamScore: 28, opponentScore: 24 },
          { week: 3, opponent: "Charlotte", location: "vs", teamScore: 31, opponentScore: 13 },
          { week: 4, opponent: "NC State", location: "at", teamScore: 31, opponentScore: 6 },
          { week: 5, note: "BYE" },
          { week: 6, opponent: "Old Dominion", location: "vs", teamScore: 31, opponentScore: 21 },
          { week: 7, opponent: "Coastal Carolina", location: "at", teamScore: 20, opponentScore: 10 },
          { week: 8, opponent: "James Madison", location: "vs", teamScore: 42, opponentScore: 7 },
          { week: 9, opponent: "Dillon", location: "at", teamScore: 14, opponentScore: 34 },
          { week: 10, opponent: "Georgia State", location: "vs", teamScore: 31, opponentScore: 38 },
          { week: 11, opponent: "Marshall", location: "at", teamScore: 28, opponentScore: 0 },
          { week: 12, opponent: "UL Monroe", location: "vs", teamScore: 56, opponentScore: 24 },
          { week: 13, opponent: "Baldwin Wallace", location: "at", teamScore: 24, opponentScore: 9, sim: true },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Patriot Tech", location: "at", neutral: true, title: "Boca Raton Bowl", round: "bowl-w1", teamScore: 39, opponentScore: 42 },
        ],
      },
      {
        team: "Dillon",
        conference: "Sun Belt",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "FCS Southeast", location: "vs", teamScore: 31, opponentScore: 7 },
          { week: 2, opponent: "Wawa University", location: "at", teamScore: 30, opponentScore: 15 },
          { week: 3, opponent: "Jacksonville State", location: "at", teamScore: 24, opponentScore: 21 },
          { week: 4, opponent: "Houston", location: "vs", teamScore: 25, opponentScore: 48 },
          { week: 5, opponent: "Coastal Carolina", location: "at", teamScore: 22, opponentScore: 24 },
          { week: 6, opponent: "James Madison", location: "vs", teamScore: 35, opponentScore: 23 },
          { week: 7, opponent: "Old Dominion", location: "at", teamScore: 24, opponentScore: 17 },
          { week: 8, note: "BYE" },
          { week: 9, opponent: "Appalachian State", location: "vs", teamScore: 34, opponentScore: 14 },
          { week: 10, opponent: "Marshall", location: "vs", teamScore: 31, opponentScore: 23 },
          { week: 11, opponent: "Georgia State", location: "at", teamScore: 35, opponentScore: 21 },
          { week: 12, opponent: "Troy", location: "at", teamScore: 37, opponentScore: 35 },
          { week: 13, opponent: "Louisiana Tech", location: "vs", teamScore: 27, opponentScore: 13 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "Arkansas State", location: "vs", neutral: true, title: "Sun Belt Championship", round: "ccg", teamScore: 23, opponentScore: 20 },
          { week: 16, opponent: "Charlotte", location: "vs", neutral: true, title: "Myrtle Beach Bowl", round: "bowl-w1", teamScore: 31, opponentScore: 28 },
        ],
      },

      /* ---------------------------- MAC ---------------------------- */
      {
        team: "Minneapolis",
        conference: "MAC",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "South Carolina", location: "at", teamScore: 13, opponentScore: 10 },
          { week: 2, opponent: "FCS Midwest", location: "vs", teamScore: 38, opponentScore: 0 },
          { week: 3, opponent: "Boise State", location: "at", teamScore: 21, opponentScore: 34 },
          { week: 4, opponent: "New Glarus", location: "vs", teamScore: 28, opponentScore: 35 },
          { week: 5, opponent: "Ohio", location: "vs", teamScore: 31, opponentScore: 6 },
          { week: 6, opponent: "Western Michigan", location: "at", teamScore: 21, opponentScore: 16 },
          { week: 7, opponent: "USF", location: "at", teamScore: 35, opponentScore: 7 },
          { week: 8, opponent: "North Shore", location: "vs", teamScore: 14, opponentScore: 21 },
          { week: 9, opponent: "Sacramento State", location: "at", teamScore: 28, opponentScore: 7 },
          { week: 10, note: "BYE" },
          { week: 11, opponent: "Bowling Green", location: "at", teamScore: 38, opponentScore: 0 },
          { week: 12, opponent: "Miami University", location: "vs", teamScore: 24, opponentScore: 7 },
          { week: 13, opponent: "Eastern Michigan", location: "at", teamScore: 31, opponentScore: 17 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "New Mexico State", location: "at", neutral: true, title: "Cure Bowl", round: "bowl-w1", teamScore: 35, opponentScore: 17 },
        ],
      },
      {
        team: "New Glarus",
        conference: "MAC",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "Westeros", location: "vs", teamScore: 34, opponentScore: 29 },
          { week: 2, opponent: "FCS Midwest", location: "vs", teamScore: 49, opponentScore: 20 },
          { week: 3, opponent: "Patriot Tech", location: "at", teamScore: 27, opponentScore: 37 },
          { week: 4, opponent: "Minneapolis", location: "at", teamScore: 35, opponentScore: 28 },
          { week: 5, opponent: "Toledo", location: "vs", teamScore: 31, opponentScore: 17 },
          { week: 6, opponent: "Rutgers", location: "at", teamScore: 35, opponentScore: 42 },
          { week: 7, opponent: "Bowling Green", location: "at", teamScore: 30, opponentScore: 20 },
          { week: 8, opponent: "Sacramento State", location: "vs", teamScore: 37, opponentScore: 7 },
          { week: 9, note: "BYE" },
          { week: 10, opponent: "UMass", location: "at", teamScore: 31, opponentScore: 6 },
          { week: 11, opponent: "Buffalo", location: "vs", teamScore: 44, opponentScore: 27 },
          { week: 12, opponent: "Ohio", location: "at", teamScore: 36, opponentScore: 29 },
          { week: 13, opponent: "Central Michigan", location: "vs", teamScore: 31, opponentScore: 24 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "North Shore", location: "vs", neutral: true, title: "MAC Championship", round: "ccg", teamScore: 31, opponentScore: 24 },
          { week: 16, opponent: "Marshall", location: "at", neutral: true, title: "68 Ventures Bowl", round: "bowl-w1", teamScore: 31, opponentScore: 30 },
        ],
      },
      {
        team: "North Shore",
        conference: "MAC",
        weeks: [
          { week: 0, note: "BYE" },
          { week: 1, opponent: "Wake Forest", location: "at", teamScore: 13, opponentScore: 37 },
          { week: 2, opponent: "FCS Midwest", location: "vs", teamScore: 42, opponentScore: 7 },
          { week: 3, opponent: "Minnesota", location: "at", teamScore: 15, opponentScore: 21 },
          { week: 4, opponent: "Baldwin Wallace", location: "vs", teamScore: 13, opponentScore: 34 },
          { week: 5, opponent: "Central Michigan", location: "at", teamScore: 55, opponentScore: 24 },
          { week: 6, opponent: "Eastern Michigan", location: "vs", teamScore: 35, opponentScore: 7 },
          { week: 7, opponent: "Miami University", location: "at", teamScore: 23, opponentScore: 13 },
          { week: 8, opponent: "Minneapolis", location: "at", teamScore: 21, opponentScore: 14 },
          { week: 9, note: "BYE" },
          { week: 10, opponent: "Ohio", location: "vs", teamScore: 17, opponentScore: 23 },
          { week: 11, opponent: "Western Michigan", location: "vs", teamScore: 30, opponentScore: 28 },
          { week: 12, opponent: "UMass", location: "at", teamScore: 41, opponentScore: 20 },
          { week: 13, opponent: "Buffalo", location: "vs", teamScore: 41, opponentScore: 7 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, opponent: "New Glarus", location: "at", neutral: true, title: "MAC Championship", round: "ccg", teamScore: 24, opponentScore: 31 },
          { week: 16, opponent: "UNLV", location: "vs", neutral: true, title: "Arizona Bowl", round: "bowl-w1", teamScore: 34, opponentScore: 31 },
        ],
      },

      /* ---------------------------- CUSA --------------------------- */
      {
        team: "Patriot Tech",
        conference: "CUSA",
        weeks: [
          { week: 0, opponent: "Missouri State", location: "vs", teamScore: 31, opponentScore: 28 },
          { week: 1, opponent: "James Madison", location: "at", teamScore: 7, opponentScore: 28 },
          { week: 2, opponent: "FCS East", location: "vs", teamScore: 7, opponentScore: 27 },
          { week: 3, opponent: "New Glarus", location: "vs", teamScore: 37, opponentScore: 27 },
          { week: 4, opponent: "Coastal Carolina", location: "at", teamScore: 38, opponentScore: 31 },
          { week: 5, opponent: "Delaware", location: "at", teamScore: 30, opponentScore: 35 },
          { week: 6, opponent: "Sam Houston", location: "vs", teamScore: 31, opponentScore: 49 },
          { week: 7, opponent: "Westeros", location: "at", teamScore: 14, opponentScore: 38 },
          { week: 8, note: "BYE" },
          { week: 9, opponent: "Wawa University", location: "vs", teamScore: 10, opponentScore: 0, sim: true },
          { week: 10, opponent: "New Mexico State", location: "at", teamScore: 28, opponentScore: 17 },
          { week: 11, opponent: "Middle Tennessee", location: "vs", teamScore: 17, opponentScore: 27 },
          { week: 12, note: "BYE" },
          { week: 13, opponent: "Kennesaw State", location: "at", teamScore: 27, opponentScore: 17 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
          { week: 16, opponent: "Appalachian State", location: "vs", neutral: true, title: "Boca Raton Bowl", round: "bowl-w1", teamScore: 42, opponentScore: 39 },
        ],
      },
      {
        team: "Wawa University",
        conference: "CUSA",
        weeks: [
          { week: 0, opponent: "Kennesaw State", location: "vs", teamScore: 24, opponentScore: 6 },
          { week: 1, opponent: "USF", location: "at", teamScore: 26, opponentScore: 21 },
          { week: 2, opponent: "Dillon", location: "vs", teamScore: 15, opponentScore: 30 },
          { week: 3, opponent: "Florida Atlantic", location: "at", teamScore: 13, opponentScore: 14 },
          { week: 4, opponent: "FCS Southeast", location: "vs", teamScore: 42, opponentScore: 17 },
          { week: 5, opponent: "Jacksonville State", location: "at", teamScore: 17, opponentScore: 19 },
          { week: 6, note: "BYE" },
          { week: 7, note: "BYE" },
          { week: 8, opponent: "Middle Tennessee", location: "vs", teamScore: 7, opponentScore: 17 },
          { week: 9, opponent: "Patriot Tech", location: "at", teamScore: 0, opponentScore: 10, sim: true },
          { week: 10, opponent: "Sam Houston", location: "vs", teamScore: 24, opponentScore: 28 },
          { week: 11, opponent: "Delaware", location: "at", teamScore: 24, opponentScore: 31 },
          { week: 12, opponent: "New Mexico State", location: "at", teamScore: 19, opponentScore: 27 },
          { week: 13, opponent: "Missouri State", location: "vs", teamScore: 37, opponentScore: 21 },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
        ],
      },
      {
        team: "Westeros",
        conference: "CUSA",
        weeks: [
          { week: 0, opponent: "Delaware", location: "vs", teamScore: 9, opponentScore: 37 },
          { week: 1, opponent: "New Glarus", location: "at", teamScore: 29, opponentScore: 34 },
          { week: 2, opponent: "Georgia Tech", location: "at", teamScore: 24, opponentScore: 27 },
          { week: 3, opponent: "California", location: "at", teamScore: 26, opponentScore: 28 },
          { week: 4, opponent: "FCS Southeast", location: "vs", teamScore: 45, opponentScore: 14 },
          { week: 5, opponent: "Missouri State", location: "vs", teamScore: 35, opponentScore: 17 },
          { week: 6, opponent: "New Mexico State", location: "at", teamScore: 10, opponentScore: 23 },
          { week: 7, opponent: "Patriot Tech", location: "vs", teamScore: 38, opponentScore: 14 },
          { week: 8, note: "BYE" },
          { week: 9, opponent: "Sam Houston", location: "at", teamScore: 30, opponentScore: 20 },
          { week: 10, opponent: "Kennesaw State", location: "at", teamScore: 28, opponentScore: 14 },
          { week: 11, opponent: "Jacksonville State", location: "vs", teamScore: 20, opponentScore: 27 },
          { week: 12, opponent: "Middle Tennessee", location: "at", teamScore: 23, opponentScore: 33 },
          { week: 13, note: "BYE" },
          { week: 14, note: "Army-Navy Week" },
          { week: 15, note: "BYE" },
        ],
      },
    ];

    /* Schedule-team-name -> roster-team-name, for cases where the
       in-game team name doesn't match the sign-up sheet verbatim.

       Empty on purpose: the short names the Team Schedule screen shows
       were expanded to full roster names during transcription, so
       nothing needs remapping. If a future screenshot is transcribed
       with shorthand (e.g. "Wawa Universit", "BaldwinWallace"), either
       expand it while transcribing or add the mapping here —
       validateData() logs a console warning for any schedule team no
       coach claims. */
    const SCHEDULE_TEAM_ALIASES = {};


    /* ---- top25-data.js ---- */
    /* ============================================================
       TOP 25 — the in-game AP poll, transcribed from screenshots
       ------------------------------------------------------------
       The 1-Star Dynasty's copy of the EA College Football 27 Top 25,
       one entry per week. It is NOT the site's own computed Power
       Rankings (that's the Rankings tab, built from head-to-head
       results). This poll is mostly CPU teams with a handful of coaches
       mixed in, and it drives two things on the site:

         1. The Top 25 tab.
         2. The "#N" rank badges on schedules. A game played in week N
            shows each team's rank from THAT week's poll, so a schedule
            always shows what a team was ranked WHEN the game was played,
            even after they rise or fall later.

       Because of (2), each week's poll is frozen history: once a week is
       entered, never edit it to reflect a later poll — add a new week
       instead.

       EMPTY ON PURPOSE
       Nobody has transcribed a 1-star poll yet. This file exists so that
       the day someone starts, the only thing needed is a screenshot —
       the data file, the tab, and the tooling are already in place and
       the first upload just works.

       An empty array is a supported state everywhere, not a half-finished
       one. script.js drops the Top 25 tab entirely when there are no
       polls, so the site shows no trace of this until the first week
       lands; schedules render every game unranked, which is correct;
       and the advance is not gated on the poll (see below), so nothing
       about the league's weekly routine changes while this sits empty.

       NO ADVANCE GATE HERE (this is the difference from main)
       The main dynasty REFUSES to advance to week N until week N's poll is
       in its file, so the poll and the new week always surface together.
       1-star is deliberately not gated: advancing never waits on a
       screenshot. Uploads are welcome any time, including weeks after the
       fact, and they appear as soon as they're pushed. See
       top25GateError() in tools/lib/league.js for where that lives.

       HOW TO START
       Screenshot the in-game Top 25 for the week, then run:

         node tools/top25.js --league 1star --week N --file poll.txt

       The --league flag is the part that's easy to forget; without it the
       script writes to main. The first upload will report every team as
       unrecognised if the poll is full of schools nobody in this league
       has played — that's what --allow-new is for. See tools/README.md.

       Start at whatever week you're on. There's no obligation to backfill
       week 1: a missing week renders as unranked, not as an error.

       Team names should match the roster / schedule spelling (the site
       resolves them the same way, through SCHEDULE_TEAM_ALIASES, so "Cal"
       vs "California" etc. still line up). `record` is whatever the poll
       shows next to the team.

         { rank, team, record }
           rank    1 = best, 1..25
           team    must resolve to a roster or schedule team name
           record  the W-L string shown in the poll (e.g. "1-0")
       ============================================================ */
    const TOP25 = [
    ];


    /* ---- cfp-data.js ---- */
    /* ============================================================
       CFP — the College Football Playoff era of the season
       ------------------------------------------------------------
       From Week 10 the in-game poll stops being the AP Top 25 and
       becomes the CFP Top 25, and the game starts showing a projected
       12-team bracket alongside it. Both are transcribed here, one
       entry per week, and both are frozen history for the same reason
       top25-data.js is: the site renders what was true THAT week, so
       editing a past week silently rewrites the record.

       WHERE THE SEASON SWITCHES OVER
       Weeks 0-9    AP poll        -> top25-data.js
       Weeks 10-14  CFP Top 25     -> CFP_POLL below
                    + projected bracket -> CFP_BRACKET below
       Week 15      Conference championships. BRACKET ONLY — this is where
                    the projection becomes the real field. No poll block:
                    week 14 is Army-Navy, the rankings don't move off that
                    game, so week 15's poll IS week 14's and the site reads
                    it through the at-or-before fallback in script.js
                    rather than storing a duplicate. The advance gate
                    knows, and won't ask you for one.
       Weeks 16-19  Bowl Weeks 1-4, one per playoff round. NOTHING is
                    transcribed here: the poll froze at week 14 and the
                    bracket is already final. Only results change, and they
                    go in postseason-data.js — the bracket fills itself in
                    from them.

       If the rankings ever DO move at week 15, add a { week: 15 } block
       the normal way: the site prefers a real block over the fallback
       automatically, and nothing here needs changing to allow it.

       That boundary lives in ONE place in the code (CFP_ERA_WEEK in
       script.js). Nothing here needs to change if the game ever moves
       it.

       ------------------------------------------------------------
       CFP_POLL — the weekly CFP Top 25
       ------------------------------------------------------------
         const CFP_POLL = [
           { week: 10, teams: [ { rank, team, record }, ... x25 ] },
           { week: 11, teams: [ ... ] },
         ];

       Exactly the shape of a TOP25 block, deliberately — the same
       renderer draws it and the same "#N" schedule badges read it, so a
       week-11 game shows a team's week-11 CFP rank. week-core.js also
       reads CFP_POLL for postseason strength-of-schedule, and takes the
       LAST entry as the poll the bracket was seeded from.

       The single-object form (`{ teams: [...] }`, no week) is also
       accepted by week-core for a season where only the final seeding
       poll was ever captured. The array form is what this file uses.

       ------------------------------------------------------------
       CFP_BRACKET — the projected 12-team field
       ------------------------------------------------------------
         const CFP_BRACKET = [
           {
             week: 10,
             projected: true,
             seeds: [
               { seed: 1,  team: "Ohio State", record: "8-0", auto: true },
               ...
               { seed: 12, team: "USF",        record: "8-0", auto: true },
             ],
             // optional — see BOWL NAMES below:
             bowls: { qf: ["Cotton Bowl", "Rose Bowl", "Fiesta Bowl", "Peach Bowl"],
                      sf: ["Orange Bowl", "Sugar Bowl"],
                      nc: "National Championship",
                      site: "Las Vegas, NV" },
           },
         ];

       TWELVE SEEDS AND NOTHING ELSE. The matchups are NOT transcribed,
       because the 12-team bracket's structure is fixed: seeds 1-4 get a
       first-round bye, and the first round is 5v12, 6v11, 7v10, 8v9,
       feeding 4, 3, 2 and 1 respectively. Deriving the lines from the
       seed list means the site cannot draw a bracket that disagrees with
       itself — there is no second copy of the pairings to fall out of
       sync. Read the seeds off the screenshot; the shape is arithmetic.

       `auto: true` is the asterisk in-game — a conference champion
       holding an automatic bid. It is display-only; it does not move a
       team's seed, because the game has already done that.

       `projected: true` means the field is a forecast, which it is every
       week from 10 through the conference championships. Set it false
       (tools/cfp.js --final) on the bracket entered after the CCGs, when
       the field is settled and the games are actually being played.

       BOWL NAMES are entered ONCE and merge forward key by key. `qf` is
       four names top to bottom; `sf` is two; `r1` is four if the game
       names the first-round sites; `nc` is the title game; `site` is
       where it's played.

       Merging matters because the assignments arrive at different times:
       the quarterfinal bowls are named on the week-10 bracket, the
       semifinal bowls only later. Taking the newest bracket's `bowls`
       whole would mean the week the semifinals appear is the week the
       quarterfinals go blank. So each name is entered on the first
       bracket that knows it and stays from then on — a fact about the
       season, not about the week.

       All of it is optional; the site renders the rounds generically
       without any of it.

       ------------------------------------------------------------
       HOW TO ADD A WEEK
       ------------------------------------------------------------
       Screenshot the in-game CFP Top 25 and the projected bracket, then:

         node tools/cfp.js --league main --week 10 \
           --poll poll.txt --bracket bracket.txt

       Do not hand-edit this file. The script counts to 25, counts to 12,
       catches a doubled rank or seed, checks every team name against the
       league's data, and refuses to overwrite a week that is already
       public history. See tools/README.md.

       WHEN IT APPEARS ON THE SITE
       Same reveal rule as the AP poll: the site shows the CFP week that
       SEASON.currentWeek has actually reached. A week entered ahead of
       the advance sits here invisible until the season catches up, and
       the main dynasty's advance to week 10+ is gated on this file
       having that week.
       ============================================================ */
    const CFP_POLL = [
      {
        week: 10,
        teams: [
          { rank: 1, team: "Miami", record: "9-0" },
          { rank: 2, team: "Ohio State", record: "7-1" },
          { rank: 3, team: "Oklahoma", record: "7-1" },
          { rank: 4, team: "Georgia", record: "7-1" },
          { rank: 5, team: "Indiana", record: "8-1" },
          { rank: 6, team: "BYU", record: "8-0" },
          { rank: 7, team: "Texas A&M", record: "7-1" },
          { rank: 8, team: "Texas Tech", record: "7-1" },
          { rank: 9, team: "LSU", record: "7-1" },
          { rank: 10, team: "Houston", record: "7-1" },
          { rank: 11, team: "Notre Dame", record: "6-2" },
          { rank: 12, team: "Texas", record: "6-2" },
          { rank: 13, team: "Iowa", record: "6-2" },
          { rank: 14, team: "Duke", record: "7-1" },
          { rank: 15, team: "Louisville", record: "6-2" },
          { rank: 16, team: "Ole Miss", record: "5-3" },
          { rank: 17, team: "Michigan", record: "5-3" },
          { rank: 18, team: "Missouri", record: "6-2" },
          { rank: 19, team: "Florida", record: "5-3" },
          { rank: 20, team: "Boise State", record: "7-1" },
          { rank: 21, team: "SMU", record: "6-2" },
          { rank: 22, team: "Florida State", record: "6-2" },
          { rank: 23, team: "Wisconsin", record: "6-2" },
          { rank: 24, team: "Arizona", record: "6-2" },
          { rank: 25, team: "Oregon", record: "5-3" },
        ],
      },
      {
        week: 11,
        teams: [
          { rank: 1, team: "Oklahoma", record: "8-1" },
          { rank: 2, team: "Miami", record: "9-0" },
          { rank: 3, team: "Georgia", record: "8-1" },
          { rank: 4, team: "Texas A&M", record: "8-1" },
          { rank: 5, team: "Indiana", record: "8-1" },
          { rank: 6, team: "LSU", record: "8-1" },
          { rank: 7, team: "Texas Tech", record: "8-1" },
          { rank: 8, team: "Notre Dame", record: "7-2" },
          { rank: 9, team: "Texas", record: "7-2" },
          { rank: 10, team: "Iowa", record: "7-2" },
          { rank: 11, team: "Ohio State", record: "7-2" },
          { rank: 12, team: "Louisville", record: "7-2" },
          { rank: 13, team: "Michigan", record: "6-3" },
          { rank: 14, team: "SMU", record: "7-2" },
          { rank: 15, team: "BYU", record: "8-1" },
          { rank: 16, team: "Florida State", record: "7-2" },
          { rank: 17, team: "Missouri", record: "6-3" },
          { rank: 18, team: "Oregon", record: "6-3" },
          { rank: 19, team: "Pittsburgh", record: "7-2" },
          { rank: 20, team: "Houston", record: "7-2" },
          { rank: 21, team: "Tennessee", record: "6-3" },
          { rank: 22, team: "Duke", record: "7-2" },
          { rank: 23, team: "TCU", record: "6-3" },
          { rank: 24, team: "Utah", record: "6-3" },
          { rank: 25, team: "Boise State", record: "7-2" },
        ],
      },
      {
        week: 12,
        teams: [
          { rank: 1, team: "Oklahoma", record: "9-1" },
          { rank: 2, team: "Miami", record: "10-0" },
          { rank: 3, team: "Georgia", record: "9-1" },
          { rank: 4, team: "Texas A&M", record: "9-1" },
          { rank: 5, team: "Indiana", record: "9-1" },
          { rank: 6, team: "Texas", record: "8-2" },
          { rank: 7, team: "Texas Tech", record: "9-1" },
          { rank: 8, team: "Ohio State", record: "8-2" },
          { rank: 9, team: "BYU", record: "9-1" },
          { rank: 10, team: "SMU", record: "8-2" },
          { rank: 11, team: "Florida State", record: "8-2" },
          { rank: 12, team: "LSU", record: "8-2" },
          { rank: 13, team: "Oregon", record: "7-3" },
          { rank: 14, team: "Notre Dame", record: "7-3" },
          { rank: 15, team: "Iowa", record: "7-3" },
          { rank: 16, team: "Utah", record: "7-3" },
          { rank: 17, team: "Boise State", record: "8-2" },
          { rank: 18, team: "Fresno State", record: "8-2" },
          { rank: 19, team: "Louisville", record: "7-3" },
          { rank: 20, team: "Nebraska", record: "7-3" },
          { rank: 21, team: "UCF", record: "7-3" },
          { rank: 22, team: "Wisconsin", record: "7-3" },
          { rank: 23, team: "Dillon", record: "9-2" },
          { rank: 24, team: "Pittsburgh", record: "7-3" },
          { rank: 25, team: "Houston", record: "7-3" },
        ],
      },
      {
        week: 13,
        teams: [
          { rank: 1, team: "Miami", record: "11-0" },
          { rank: 2, team: "Texas A&M", record: "10-1" },
          { rank: 3, team: "Indiana", record: "10-1" },
          { rank: 4, team: "Texas", record: "9-2" },
          { rank: 5, team: "Oklahoma", record: "9-2" },
          { rank: 6, team: "Texas Tech", record: "10-1" },
          { rank: 7, team: "Ohio State", record: "9-2" },
          { rank: 8, team: "BYU", record: "10-1" },
          { rank: 9, team: "LSU", record: "9-2" },
          { rank: 10, team: "Notre Dame", record: "8-3" },
          { rank: 11, team: "Georgia", record: "9-2" },
          { rank: 12, team: "Oregon", record: "8-3" },
          { rank: 13, team: "Utah", record: "8-3" },
          { rank: 14, team: "Iowa", record: "8-3" },
          { rank: 15, team: "Boise State", record: "9-2" },
          { rank: 16, team: "Fresno State", record: "9-2" },
          { rank: 17, team: "Louisville", record: "8-3" },
          { rank: 18, team: "UCF", record: "8-3" },
          { rank: 19, team: "Wisconsin", record: "8-3" },
          { rank: 20, team: "SMU", record: "8-3" },
          { rank: 21, team: "Florida State", record: "8-3" },
          { rank: 22, team: "Dillon", record: "9-2" },
          { rank: 23, team: "Duke", record: "8-3" },
          { rank: 24, team: "Houston", record: "8-3" },
          { rank: 25, team: "Penn State", record: "7-4" },
        ],
      },
      {
        week: 14,
        teams: [
          { rank: 1, team: "Texas A&M", record: "11-1" },
          { rank: 2, team: "Miami", record: "12-0" },
          { rank: 3, team: "Indiana", record: "11-1" },
          { rank: 4, team: "Texas Tech", record: "11-1" },
          { rank: 5, team: "Ohio State", record: "10-2" },
          { rank: 6, team: "BYU", record: "11-1" },
          { rank: 7, team: "LSU", record: "10-2" },
          { rank: 8, team: "Notre Dame", record: "9-3" },
          { rank: 9, team: "Georgia", record: "10-2" },
          { rank: 10, team: "Boise State", record: "10-2" },
          { rank: 11, team: "Texas", record: "9-3" },
          { rank: 12, team: "Oklahoma", record: "9-3" },
          { rank: 13, team: "Louisville", record: "9-3" },
          { rank: 14, team: "Wisconsin", record: "9-3" },
          { rank: 15, team: "Florida State", record: "9-3" },
          { rank: 16, team: "Virginia", record: "8-4" },
          { rank: 17, team: "Dillon", record: "10-2" },
          { rank: 18, team: "Duke", record: "9-3" },
          { rank: 19, team: "Penn State", record: "8-4" },
          { rank: 20, team: "Appalachian State", record: "10-2" },
          { rank: 21, team: "UNLV", record: "9-3" },
          { rank: 22, team: "Fresno State", record: "9-3" },
          { rank: 23, team: "Minneapolis", record: "9-3" },
          { rank: 24, team: "New Glarus", record: "10-2" },
          { rank: 25, team: "Nebraska", record: "8-4" },
        ],
      },
      {
        week: 15,
        teams: [
          { rank: 1, team: "Ohio State", record: "11-2" },
          { rank: 2, team: "BYU", record: "12-1" },
          { rank: 3, team: "LSU", record: "11-2" },
          { rank: 4, team: "Texas A&M", record: "11-2" },
          { rank: 5, team: "Indiana", record: "11-2" },
          { rank: 6, team: "Texas Tech", record: "11-2" },
          { rank: 7, team: "Miami", record: "12-1" },
          { rank: 8, team: "Notre Dame", record: "9-3" },
          { rank: 9, team: "Georgia", record: "10-2" },
          { rank: 10, team: "Boise State", record: "10-2" },
          { rank: 11, team: "Texas", record: "9-3" },
          { rank: 12, team: "Oklahoma", record: "9-3" },
          { rank: 13, team: "Louisville", record: "9-3" },
          { rank: 14, team: "Wisconsin", record: "9-3" },
          { rank: 15, team: "Florida State", record: "9-3" },
          { rank: 16, team: "Dillon", record: "11-2" },
          { rank: 17, team: "Virginia", record: "8-4" },
          { rank: 18, team: "Duke", record: "9-3" },
          { rank: 19, team: "Penn State", record: "8-4" },
          { rank: 20, team: "Fresno State", record: "10-3" },
          { rank: 21, team: "Appalachian State", record: "10-2" },
          { rank: 22, team: "Minneapolis", record: "9-3" },
          { rank: 23, team: "New Glarus", record: "11-2" },
          { rank: 24, team: "Nebraska", record: "8-4" },
          { rank: 25, team: "UNLV", record: "9-4" },
        ],
      },
    ];

    const CFP_BRACKET = [
      {
        week: 10,
        projected: true,
        seeds: [
          { seed:  1, team: "Miami", record: "9-0", auto: true },
          { seed:  2, team: "Ohio State", record: "7-1", auto: true },
          { seed:  3, team: "Oklahoma", record: "7-1" },
          { seed:  4, team: "Georgia", record: "7-1", auto: true },
          { seed:  5, team: "Indiana", record: "8-1" },
          { seed:  6, team: "BYU", record: "8-0", auto: true },
          { seed:  7, team: "Texas A&M", record: "7-1" },
          { seed:  8, team: "Texas Tech", record: "7-1" },
          { seed:  9, team: "LSU", record: "7-1" },
          { seed: 10, team: "Houston", record: "7-1" },
          { seed: 11, team: "Notre Dame", record: "6-2", auto: true },
          { seed: 12, team: "Boise State", record: "7-1", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Peach Bowl", "Fiesta Bowl", "Rose Bowl"],
          site: "Las Vegas, NV",
        },
      },
      {
        week: 11,
        projected: true,
        seeds: [
          { seed:  1, team: "Oklahoma", record: "8-1" },
          { seed:  2, team: "Miami", record: "9-0", auto: true },
          { seed:  3, team: "Georgia", record: "8-1", auto: true },
          { seed:  4, team: "Texas A&M", record: "8-1" },
          { seed:  5, team: "Indiana", record: "8-1" },
          { seed:  6, team: "LSU", record: "8-1" },
          { seed:  7, team: "Texas Tech", record: "8-1" },
          { seed:  8, team: "Notre Dame", record: "7-2", auto: true },
          { seed:  9, team: "Texas", record: "7-2" },
          { seed: 10, team: "Ohio State", record: "7-2", auto: true },
          { seed: 11, team: "BYU", record: "8-1", auto: true },
          { seed: 12, team: "Boise State", record: "7-2", auto: true },
        ],
        bowls: {
          site: "Las Vegas, NV",
        },
      },
      {
        week: 12,
        projected: true,
        seeds: [
          { seed:  1, team: "Oklahoma", record: "9-1" },
          { seed:  2, team: "Miami", record: "10-0", auto: true },
          { seed:  3, team: "Georgia", record: "9-1", auto: true },
          { seed:  4, team: "Texas A&M", record: "9-1" },
          { seed:  5, team: "Indiana", record: "9-1" },
          { seed:  6, team: "Texas", record: "8-2" },
          { seed:  7, team: "Texas Tech", record: "9-1", auto: true },
          { seed:  8, team: "Ohio State", record: "8-2", auto: true },
          { seed:  9, team: "BYU", record: "9-1" },
          { seed: 10, team: "SMU", record: "8-2" },
          { seed: 11, team: "Florida State", record: "8-2" },
          { seed: 12, team: "Boise State", record: "8-2", auto: true },
        ],
        bowls: {
          qf: ["Rose Bowl", "Peach Bowl", "Cotton Bowl", "Fiesta Bowl"],
          site: "Las Vegas, NV",
        },
      },
      {
        week: 13,
        projected: true,
        seeds: [
          { seed:  1, team: "Miami", record: "11-0", auto: true },
          { seed:  2, team: "Texas A&M", record: "10-1", auto: true },
          { seed:  3, team: "Indiana", record: "10-1" },
          { seed:  4, team: "Texas", record: "9-2" },
          { seed:  5, team: "Oklahoma", record: "9-2" },
          { seed:  6, team: "Texas Tech", record: "10-1", auto: true },
          { seed:  7, team: "Ohio State", record: "9-2", auto: true },
          { seed:  8, team: "BYU", record: "10-1" },
          { seed:  9, team: "LSU", record: "9-2" },
          { seed: 10, team: "Notre Dame", record: "8-3", auto: true },
          { seed: 11, team: "Georgia", record: "9-2" },
          { seed: 12, team: "Boise State", record: "9-2", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Peach Bowl", "Rose Bowl", "Fiesta Bowl"],
          site: "Las Vegas, NV",
        },
      },
      {
        week: 14,
        projected: true,
        seeds: [
          { seed:  1, team: "Texas A&M", record: "11-1", auto: true },
          { seed:  2, team: "Miami", record: "12-0", auto: true },
          { seed:  3, team: "Indiana", record: "11-1" },
          { seed:  4, team: "Texas Tech", record: "11-1", auto: true },
          { seed:  5, team: "Ohio State", record: "10-2", auto: true },
          { seed:  6, team: "BYU", record: "11-1" },
          { seed:  7, team: "LSU", record: "10-2" },
          { seed:  8, team: "Notre Dame", record: "9-3", auto: true },
          { seed:  9, team: "Georgia", record: "10-2" },
          { seed: 10, team: "Boise State", record: "10-2", auto: true },
          { seed: 11, team: "Texas", record: "9-3" },
          { seed: 12, team: "Oklahoma", record: "9-3" },
        ],
        bowls: {
          site: "Las Vegas, NV",
        },
      },
      {
        week: 15,
        projected: false,
        seeds: [
          { seed:  1, team: "Ohio State", record: "11-2", auto: true },
          { seed:  2, team: "BYU", record: "12-1", auto: true },
          { seed:  3, team: "LSU", record: "11-2", auto: true },
          { seed:  4, team: "Texas A&M", record: "11-2" },
          { seed:  5, team: "Indiana", record: "11-2" },
          { seed:  6, team: "Texas Tech", record: "11-2" },
          { seed:  7, team: "Miami", record: "12-1" },
          { seed:  8, team: "Notre Dame", record: "9-3", auto: true },
          { seed:  9, team: "Georgia", record: "10-2" },
          { seed: 10, team: "Boise State", record: "10-2", auto: true },
          { seed: 11, team: "Texas", record: "9-3" },
          { seed: 12, team: "SMU", record: "9-4", auto: true },
        ],
        bowls: {
          qf: ["Cotton Bowl", "Rose Bowl", "Fiesta Bowl", "Peach Bowl"],
          site: "Las Vegas, NV",
        },
      },
    ];


    /* ---- postseason-data.js ---- */
    /* ============================================================
       POSTSEASON — conference championships, the CFP, and bowls
       ------------------------------------------------------------
       Everything played after the regular season. Format and rationale
       are documented in full at buildPostseason() in week-core.js and in
       docs/seasons-and-postseason.md; the short version is below.

         const POSTSEASON = {
           rounds: [
             { id: "ccg", label: "Conference Championships", games: [
               { home: "Georgia", away: "Texas", title: "SEC Championship",
                 neutral: true, stadium: "Mercedes-Benz Stadium",
                 homeScore: 31, awayScore: 24 },
             ]},
             { id: "cfp-r1", label: "CFP First Round",       games: [ ... ] },
             { id: "cfp-qf", label: "CFP Quarterfinal",      games: [ ... ] },
             { id: "cfp-sf", label: "CFP Semifinal",         games: [ ... ] },
             { id: "cfp-nc", label: "National Championship", games: [ ... ] },
             { id: "bowl",   label: "Bowl Games",            games: [ ... ] },
           ],
         };

       ONE ROW PER GAME, unlike the regular season, which stores a game
       twice — once on each team's week list. That redundancy is a
       liability for a handful of one-off neutral-site games: writing a
       game twice is how home/away disagreements and half-entered scores
       get in. One row per game removes the entire class of error.

       Rounds render in array order. There is no `order` field, so
       inserting a round means putting it in the right place.

       Omit both scores for a game that hasn't been played.

       THE FOUR cfp-* IDS ARE LOAD-BEARING. The CFP bracket on the Top 25
       tab advances its slots by looking for a played game between two
       known teams inside `cfp-r1`, `cfp-qf`, `cfp-sf` and `cfp-nc`, in
       that order. Rename one and the bracket quietly stops filling in
       past that round — it won't error, it will just show the rest of
       the field as undecided. The `label` beside each id is free text
       and safe to change.

       Empty is a valid state and the normal one until December.
       ============================================================ */
    const POSTSEASON = {
      rounds: [
        /* Week 15 conference championships, transcribed from the
           national Scores/Schedules screen 2026-08-20. Not yet played
           (kickoff time only, no result).

           Sun Belt (Dillon) and MAC (North Shore/New Glarus) both have a
           1-star coached team in their title game, so those two live as
           ordinary rows on those teams' own schedules in
           schedule-data.js instead — see that file's header. The CUSA
           title game is New Mexico State vs Delaware, neither of which
           any 1-star coach plays, so it goes here.

           Neutral site (no confirmed host stadium for this game in the
           engine); home/away below is arbitrary since neither score is
           in yet. */
        { id: "ccg", label: "Conference Championships", games: [
          { home: "Delaware", away: "New Mexico State", title: "C-USA Championship",
            neutral: true },
        ]},
      ],
    };


    /* The same shape script.js assembles for the live season, so
       computeRankings / computeH2H / computeAchievements can't tell
       an archived season from the current one. */
    return {
      SEASON: typeof SEASON !== "undefined" ? SEASON : {},
      COACHES: typeof COACHES !== "undefined" ? COACHES : [],
      ALIASES: typeof SCHEDULE_TEAM_ALIASES !== "undefined" ? SCHEDULE_TEAM_ALIASES : {},
      TEAM_SCHEDULES: typeof TEAM_SCHEDULES !== "undefined" ? TEAM_SCHEDULES : [],
      TOP25: typeof TOP25 !== "undefined" ? TOP25 : [],
      POSTSEASON: typeof POSTSEASON !== "undefined" ? POSTSEASON : null,
      CFP_POLL: typeof CFP_POLL !== "undefined" ? CFP_POLL : null,
      CFP_BRACKET: typeof CFP_BRACKET !== "undefined" ? CFP_BRACKET : null,
    };
  })();

  /* THE FOLDER NAME WINS over the file's own SEASON.year — the same
     tiebreak loadCareer() applies, for the same reason: the folder is
     the thing a human can see and sort. */
  season.SEASON = Object.assign({}, season.SEASON, { year: 2026 });

  /* Oldest first. Script tags run in document order and each archive
     pushes as it loads, so index.html listing the years in order is
     what keeps CAREER sorted — computeRankings applies throughWeek to
     the LAST entry only, so a reversed list would cap the wrong
     season. */
  var all = (window.ARCHIVED_SEASONS = window.ARCHIVED_SEASONS || []);
  all.push(season);
})();
