#!/usr/bin/env python3
"""
============================================================
MAKE-OG-IMAGES — link preview cards, one per league
------------------------------------------------------------
Regenerates og-image.png for every league in the league accent
colour. These are what Discord, iMessage and Slack show when
somebody pastes a link, so each league needs its own or a 3-star
link previews as the main dynasty.

    python3 tools/make-og-images.py

Writes:
    og-image.png          community — the landing page (gold, no league name)
    main/og-image.png     main   (gold)
    3star/og-image.png    3-star (ice blue)
    1star/og-image.png    1-star (copper)

FONTS
    The site uses Oswald and JetBrains Mono from Google Fonts.
    Neither ships with this image pipeline, so the closest
    metric-compatible substitutes are used instead:
        Oswald         -> Liberation Sans Narrow Bold
        JetBrains Mono -> DejaVu Sans Mono Bold
    All three cards are generated by this same script, so they
    match each other exactly. If you ever want true Oswald,
    install the TTF and point DISPLAY_FONT at it, then re-run —
    all three regenerate together and stay consistent.

Requires Pillow.  pip install pillow
============================================================
"""

from PIL import Image, ImageDraw, ImageFont
import os

W, H = 1200, 630

NAVY_DEEP = (6, 11, 22)
NAVY_PANEL = (16, 29, 51)
CHALK = (242, 244, 248)
STEEL = (127, 139, 163)

DISPLAY_FONT = "/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf"
MONO_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

GOLD = (242, 193, 78)
ICE = (78, 195, 242)
COPPER = (242, 137, 78)

# (folder, tagline, subline, accent, chips)
#
# The root card is the community one — it fronts the landing page,
# which is about all three dynasties rather than any single league.
# It keeps the gold identity but carries no league name, and shows
# the three accents as chips so it reads as the set rather than as
# the main dynasty wearing a different subtitle.
CARDS = [
    ("",      "THREE DYNASTIES", "MAIN  ·  3-STAR  ·  1-STAR",            GOLD,   [GOLD, ICE, COPPER]),
    ("main",  "MAIN DYNASTY",    "SCHEDULE  ·  POWER RANKINGS  ·  ROSTER", GOLD,   []),
    ("3star", "3-STAR DYNASTY",  "SCHEDULE  ·  POWER RANKINGS  ·  ROSTER", ICE,    []),
    ("1star", "1-STAR DYNASTY",  "SCHEDULE  ·  POWER RANKINGS  ·  ROSTER", COPPER, []),
]


def blend(c1, c2, t):
    return tuple(round(a + (b - a) * t) for a, b in zip(c1, c2))


def build(tag, subline, accent, chips):
    img = Image.new("RGB", (W, H), NAVY_DEEP)
    d = ImageDraw.Draw(img, "RGBA")

    # Vertical wash, deep at the bottom like the site background.
    for y in range(H):
        d.line([(0, y), (W, y)], fill=blend((13, 22, 38), NAVY_DEEP, y / H))

    # Lighter wedge on the left, cut on the diagonal — the same angled
    # language as the panels and buttons on the site.
    #
    # Built as its own gradient and pasted through a polygon mask.
    # Stacking translucent polygons instead looks fine for two or three
    # and then compounds: at 70 layers the "faint" tint had built up
    # into a solid olive slab.
    wedge = Image.new("RGB", (W, H))
    wd = ImageDraw.Draw(wedge)
    for y in range(H):
        t = y / H
        # Warm dark at the top, fading to the page navy by the bottom.
        wd.line([(0, y), (W, y)], fill=blend(blend(accent, NAVY_PANEL, 0.86), NAVY_DEEP, t))

    mask = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mask).polygon([(0, 0), (390, 0), (215, H), (0, H)], fill=255)
    img.paste(wedge, (0, 0), mask)

    # Faint diagonal pinstripes across the whole card.
    for x in range(-H, W + H, 46):
        d.line([(x, 0), (x + H, H)], fill=(255, 255, 255, 5), width=1)

    d.rectangle([0, 0, W, 4], fill=accent)                       # top rule
    d.polygon([(W, H), (W, H - 120), (W - 120, H)], fill=accent)  # corner flag

    f_badge = ImageFont.truetype(MONO_FONT, 25)
    f_ncaa = ImageFont.truetype(DISPLAY_FONT, 138)
    f_legends = ImageFont.truetype(DISPLAY_FONT, 138)
    f_tag = ImageFont.truetype(MONO_FONT, 27)
    f_sub = ImageFont.truetype(MONO_FONT, 24)

    # Badge, top right — a parallelogram matching .league-badge.
    label = "EA COLLEGE FOOTBALL 27"
    tw = d.textlength(label, font=f_badge)
    bx2, by1, by2 = W - 78, 88, 138
    bx1 = bx2 - tw - 44
    d.polygon(
        [(bx1 + 14, by1), (bx2, by1), (bx2 - 14, by2), (bx1, by2)], fill=accent
    )
    d.text((bx1 + 22, by1 + 10), label, font=f_badge, fill=NAVY_DEEP)

    # The // mark, drawn as two slanted bars rather than glyphs so the
    # angle matches the site exactly.
    for i in range(2):
        x = 104 + i * 46
        d.polygon(
            [(x + 30, 196), (x + 62, 196), (x + 32, 306), (x, 306)], fill=accent
        )

    d.text((210, 178), "NCAA", font=f_ncaa, fill=CHALK)
    d.text((210, 310), "LEGENDS", font=f_legends, fill=accent)

    d.text((212, 466), tag, font=f_tag, fill=STEEL)
    d.text((212, 508), subline, font=f_sub, fill=STEEL)

    # Community card only: one angled chip per league, in league order,
    # so the card shows the whole set at a glance.
    for i, c in enumerate(chips):
        x = 212 + i * 58
        d.polygon([(x + 8, 560), (x + 46, 560), (x + 38, 574), (x, 574)], fill=c)

    return img


def main():
    import sys

    # The root og-image.png was made with real Oswald before this
    # script existed. Regenerating it here would silently swap it for
    # the substitute font, so it's left alone unless you ask.
    # --include-main rebuilds all three, which is what you want if you
    # care more about the set matching each other than about keeping
    # the original.
    include_main = "--include-main" in sys.argv

    for d_name, tag, subline, accent, chips in CARDS:
        # main/og-image.png predates this script and was made with real
        # Oswald. Rebuilding it here would quietly swap in the
        # substitute font, so it's left alone unless asked.
        if d_name == "main" and not include_main:
            print("  main/og-image.png        skipped (use --include-main to rebuild)")
            continue
        out_dir = os.path.join(ROOT, d_name) if d_name else ROOT
        os.makedirs(out_dir, exist_ok=True)
        out = os.path.join(out_dir, "og-image.png")
        build(tag, subline, accent, chips).save(out, optimize=True)
        size = os.path.getsize(out) / 1024
        print(f"  {out.replace(ROOT + os.sep, ''):24} {size:6.1f} KB  {tag}")


if __name__ == "__main__":
    main()
